(()=>{
const BASE='https://zoryq-evm-node-live-production.up.railway.app',RPC=BASE+'/rpc',PUBLIC_START='https://zoryq-testnet.vercel.app/start';
const SWAP='0x8205F34B803eDd79DDCA414F00e12eCdDEdDacbE'.toLowerCase(),STAKE='0xbB26FaADD1E083C7c0dc0A82Ddb96cC45253Ecb1'.toLowerCase();
const $=id=>document.getElementById(id);let lastScan={swap:0,stake:0};
async function account(){try{const a=await ethereum.request({method:'eth_accounts'});return a?.[0]?.toLowerCase()||null}catch{return null}}
async function rpc(method,params=[]){const r=await fetch(RPC,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({jsonrpc:'2.0',id:1,method,params})}),j=await r.json();if(j.error)throw Error(j.error.message);return j.result}
async function action(name,extra={}){const a=await account();if(!a)throw Error('Connect wallet first');const r=await fetch(BASE+'/genesis/action',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({address:a,action:name,...extra})}),j=await r.json();if(!r.ok)throw Error(j.error||'Genesis action failed');await status();return j}
async function status(){const a=await account();if(!a)return;try{const r=await fetch(BASE+'/genesis/status?address='+encodeURIComponent(a)),j=await r.json();if(!j.ok)return;const el=$('zoryqGenesisStatus');if(el)el.innerHTML=`<div style="font-size:10px;letter-spacing:.12em;color:#75d8ff">GENESIS TESTNET USER</div><strong style="display:block;font-size:22px;margin:4px 0">${j.genesis.completed}/${j.genesis.total} core actions</strong><div style="color:#91a5bd">Pending Score <b style="color:#f5f8ff">${j.pendingScore}</b> · Onchain verified <b style="color:#48dc97">${j.verifiedOnchainScore}</b> · Social pending <b style="color:#ffd070">${j.socialPendingScore}</b> · Finalized <b>${j.finalizedOnchainScore}</b></div><div style="font-size:11px;color:#71849d;margin-top:7px">${j.genesis.eligible?'Genesis requirements complete — pending Score finalization.':'Complete Follow X, Faucet, Swap and Stake.'}</div>`}catch{}}
function validXPostUrl(v){try{const u=new URL(v.trim());return (u.hostname==='x.com'||u.hostname==='www.x.com')&&/^\/[A-Za-z0-9_]+\/status\/\d+/.test(u.pathname)}catch{return false}}
function installUi(){const social=document.querySelector('.social');if(social&&!$('zoryqShareQuest')){const box=document.createElement('div');box.id='zoryqShareQuest';box.style.cssText='margin-top:14px;padding-top:14px;border-top:1px solid #24415e';const text=encodeURIComponent(`I'm testing the ZORYQ Genesis Testnet ⚡ Join: ${PUBLIC_START} @ZORIQNetwork`);box.innerHTML=`<strong>Share Genesis · +200 pending Score</strong><p>Share the official Genesis Testnet invitation on X. One reward per campaign; duplicate proof URLs do not count.</p><div style="display:flex;gap:8px;flex-wrap:wrap"><a class="btn" target="_blank" rel="noopener noreferrer" href="https://x.com/intent/post?text=${text}">Share on X ↗</a></div><input id="zoryqShareProof" class="input" style="margin-top:10px" placeholder="Paste your X post URL: https://x.com/you/status/..."><button id="zoryqShareClaim" class="btn" type="button">Record share proof</button><div id="zoryqShareMsg" class="msg">+200 remains pending until X OAuth/API verification is enabled.</div>`;social.appendChild(box);$('zoryqShareClaim').onclick=async()=>{try{const proof=$('zoryqShareProof').value.trim();if(!validXPostUrl(proof))throw Error('Paste a valid x.com post URL first.');const j=await action('x_share',{campaignId:'genesis-share-v1',proofRef:proof});$('zoryqShareMsg').innerHTML='<span class="ok">+200 pending Score recorded with X post proof.</span>'+(j.duplicate?' Already counted for this campaign.':'')}catch(e){$('zoryqShareMsg').innerHTML='<span class="bad">'+e.message+'</span>'}}}
const aside=document.querySelector('aside.card');if(aside&&!$('zoryqGenesisStatus')){const el=document.createElement('div');el.id='zoryqGenesisStatus';el.style.cssText='margin-top:14px;border:1px solid #24415e;border-radius:14px;padding:14px;background:#0b111a';el.innerHTML='Connect wallet to load Genesis Score.';aside.appendChild(el)}
const follow=$('follow');if(follow)follow.addEventListener('change',async()=>{if(follow.checked){try{await action('x_follow',{xHandle:'@ZORIQNetwork',campaignId:'genesis-follow-v1',proofRef:'self-attested-follow'})}catch{}}});
const swap=$('swap'),stake=$('stake');if(swap)swap.addEventListener('click',()=>watchTx('swap',SWAP));if(stake)stake.addEventListener('click',()=>watchTx('stake',STAKE));
}
async function watchTx(kind,target){const a=await account();if(!a)return;let from=Number(BigInt(await rpc('eth_blockNumber')));lastScan[kind]=Math.max(lastScan[kind],from);for(let n=0;n<30;n++){await new Promise(r=>setTimeout(r,3000));const latest=Number(BigInt(await rpc('eth_blockNumber')));for(let b=Math.max(from,lastScan[kind]);b<=latest;b++){const block=await rpc('eth_getBlockByNumber',['0x'+b.toString(16),true]);for(const tx of block?.transactions||[]){if(String(tx.from||'').toLowerCase()===a&&String(tx.to||'').toLowerCase()===target){try{await action(kind,{txHash:tx.hash});lastScan[kind]=b+1;return}catch{}}}}lastScan[kind]=latest+1;from=latest+1}}
window.addEventListener('load',()=>{installUi();status();setInterval(status,7000);if(window.ethereum)ethereum.on?.('accountsChanged',()=>setTimeout(status,300))});
})();
