import http from 'node:http';
import fs from 'node:fs';
import path from 'node:path';
import { spawn } from 'node:child_process';

const PORT=Number(process.env.PORT||8080),APP_PORT=8082,ADMIN_PORT=8083;
const WEB_ROOT='/app/web',PROTOCOL_ROOT='/app/protocol-out';
const app=spawn(process.execPath,['public-gateway.mjs'],{stdio:'inherit',env:{...process.env,PORT:String(APP_PORT)}});
const admin=spawn(process.execPath,['admin-control.mjs'],{stdio:'inherit',env:{...process.env,PORT:String(ADMIN_PORT)}});
function childExit(name){return(code,signal)=>{console.error(`${name} exited`,{code,signal});process.exit(code||1)}}
app.on('exit',childExit('ZORYQ public gateway'));admin.on('exit',childExit('ZORYQ admin control verifier'));
process.on('SIGTERM',()=>{app.kill('SIGTERM');admin.kill('SIGTERM')});process.on('SIGINT',()=>{app.kill('SIGINT');admin.kill('SIGINT')});
const txRoute=/^\/tx\/0x[0-9a-fA-F]{64}$/,addressRoute=/^\/address\/0x[0-9a-fA-F]{40}$/,blockRoute=/^\/block\/(?:0x[0-9a-fA-F]+|[0-9]+)$/,tokenRoute=/^\/token\/0x[0-9a-fA-F]{40}$/;
const protocolArtifacts=new Map([['/protocol-artifacts/dexV1.json','ZoryqDexV1.sol/ZoryqDexV1.json'],['/protocol-artifacts/lending.json','ZoryqLendingLab.sol/ZoryqLendingLab.json'],['/protocol-artifacts/projectRegistry.json','ZoryqProjectRegistry.sol/ZoryqProjectRegistry.json']]);
const I18N_INJECT='<script src="/i18n.js"></script><script src="/page-i18n.js"></script>';
function servePath(req,res,root,file,contentType='text/html; charset=utf-8'){const full=path.resolve(root,file);if(!full.startsWith(path.resolve(root)+path.sep)||!fs.existsSync(full)||!fs.statSync(full).isFile()){res.writeHead(404,{'content-type':'application/json; charset=utf-8'});return res.end(JSON.stringify({ok:false,error:'not_found'}))}res.writeHead(200,{'content-type':contentType,'cache-control':contentType.startsWith('text/html')?'no-cache':'public, max-age=300','x-zoryq-route':'public-edge','access-control-allow-origin':'*'});if(req.method==='HEAD')return res.end();if(contentType.startsWith('text/html')){let html=fs.readFileSync(full,'utf8');if(!html.includes('/i18n.js'))html=html.replace('</body>',I18N_INJECT+'</body>');return res.end(html)}fs.createReadStream(full).pipe(res)}
function serveFile(req,res,file,contentType='text/html; charset=utf-8'){return servePath(req,res,WEB_ROOT,file,contentType)}
function proxyTo(port,req,res){const p=http.request({hostname:'127.0.0.1',port,path:req.url,method:req.method,headers:{...req.headers,host:`127.0.0.1:${port}`}},u=>{res.writeHead(u.statusCode||502,u.headers);u.pipe(res)});p.on('error',e=>{res.writeHead(503,{'content-type':'application/json; charset=utf-8'});res.end(JSON.stringify({ok:false,error:'gateway_unavailable',detail:e.message}))});req.pipe(p)}
function proxy(req,res){return proxyTo(APP_PORT,req,res)}
http.createServer((req,res)=>{const url=new URL(req.url||'/','http://localhost'),readable=req.method==='GET'||req.method==='HEAD';if(url.pathname.startsWith('/admin/control/'))return proxyTo(ADMIN_PORT,req,res);if(readable&&protocolArtifacts.has(url.pathname))return servePath(req,res,PROTOCOL_ROOT,protocolArtifacts.get(url.pathname),'application/json; charset=utf-8');if(readable&&(txRoute.test(url.pathname)||addressRoute.test(url.pathname)||blockRoute.test(url.pathname)||tokenRoute.test(url.pathname)))return serveFile(req,res,'explorer.html');
const htmlRoutes=[[['/faucet','/faucet.html'],'faucet.html'],[['/swap','/swap.html'],'swap.html'],[['/stake','/stake.html'],'stake.html'],[['/lending','/lending.html'],'lending.html'],[['/developer','/developers','/developer.html'],'developer.html'],[['/why','/thesis','/why-zoryq','/why-zoryq.html'],'why-zoryq.html'],[['/ideas','/build-ideas','/ideas.html'],'ideas.html'],[['/devkit','/devkit.html'],'devkit.html'],[['/launch-project','/project-launch','/project-launch.html'],'project-launch.html'],[['/build','/quickstart','/build.html'],'build.html'],[['/metrics','/traction','/metrics.html'],'metrics.html'],[['/ecosystem','/ecosystem.html'],'ecosystem.html'],[['/builders','/challenge','/builder-challenge','/builder-challenge.html'],'builder-challenge.html'],[['/investors','/investor','/investor.html'],'investor.html'],[['/node-operators','/operators','/node-operators.html'],'node-operators.html'],[['/intelligence','/genesis-intelligence','/intelligence.html'],'intelligence.html'],[['/admin-control','/admin-control.html'],'admin-control.html'],[['/protocol-launch','/protocol-launch.html'],'protocol-launch.html'],[['/network-maturity','/network-maturity.html'],'network-maturity.html']];for(const [routes,file] of htmlRoutes)if(readable&&routes.includes(url.pathname))return serveFile(req,res,file);
if(readable&&url.pathname==='/devkit/network.json')return serveFile(req,res,'devkit-network.json','application/json; charset=utf-8');if(readable&&url.pathname==='/devkit/viem.mjs')return serveFile(req,res,'devkit-viem.mjs','application/javascript; charset=utf-8');if(readable&&url.pathname==='/devkit/HelloZoryq.sol')return serveFile(req,res,'devkit-HelloZoryq.sol','text/plain; charset=utf-8');if(readable&&url.pathname==='/network-maturity.json')return serveFile(req,res,'network-maturity.json','application/json; charset=utf-8');if(readable&&url.pathname==='/defi-common.js')return serveFile(req,res,'defi-common.js','application/javascript; charset=utf-8');if(readable&&url.pathname==='/i18n.js')return serveFile(req,res,'i18n.js','application/javascript; charset=utf-8');if(readable&&url.pathname==='/i18n-content.js')return serveFile(req,res,'i18n-content.js','application/javascript; charset=utf-8');if(readable&&url.pathname==='/page-i18n.js')return serveFile(req,res,'page-i18n.js','application/javascript; charset=utf-8');if(readable&&url.pathname==='/llms.txt')return serveFile(req,res,'llms.txt','text/plain; charset=utf-8');if(readable&&url.pathname==='/.well-known/zoryq-agent.json')return serveFile(req,res,'.well-known-zoryq-agent.json','application/json; charset=utf-8');if(readable&&url.pathname==='/agent/action-schema.json')return serveFile(req,res,'zoryq-action-schema.json','application/schema+json; charset=utf-8');if(readable&&url.pathname==='/agent/project-schema.json')return serveFile(req,res,'zoryq-project-schema.json','application/schema+json; charset=utf-8');if(readable&&url.pathname==='/agent/project-intelligence-schema.json')return serveFile(req,res,'project-intelligence-schema.json','application/schema+json; charset=utf-8');if(readable&&url.pathname==='/agent/builder-reputation.json')return serveFile(req,res,'builder-reputation.json','application/json; charset=utf-8');return proxy(req,res)}).listen(PORT,'0.0.0.0',()=>console.log(`ZORYQ edge gateway listening on :${PORT}; app :${APP_PORT}; admin :${ADMIN_PORT}`));