import {useState} from 'react';
import {router} from 'expo-router';
import {Pressable,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {KyvoLogo} from '@/components/KyvoLogo';
import {Card,GlowButton,SectionTitle} from '@/components/Ui';
import {IntentPlan,planIntent} from '@/services/intent';
import {colors} from '@/theme/colors';

export default function OneScreen(){const [intent,setIntent]=useState('');const [plan,setPlan]=useState<IntentPlan|null>(null);return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><View style={s.head}><KyvoLogo/><Pressable onPress={()=>router.back()}><Text style={s.close}>×</Text></Pressable></View><Text style={s.title}>KYVO ONE</Text><Text style={s.hero}>Crypto without complexity.</Text><Text style={s.sub}>Diga o resultado que você quer. A KYVO ONE planeja rede, rota, swap/bridge, custo e segurança antes de pedir sua assinatura.</Text><Card><TextInput multiline value={intent} onChangeText={setIntent} placeholder="Ex.: Quero enviar 500 USDC para @michael da forma mais barata" placeholderTextColor="#55596A" style={s.input}/><GlowButton title="Criar plano" lime onPress={async()=>setPlan(await planIntent(intent))}/></Card>{plan?<Card><SectionTitle title="PLANO DE EXECUÇÃO"/><Text style={s.summary}>{plan.summary}</Text>{plan.steps.map((step,i)=><View key={step} style={s.step}><View style={s.num}><Text style={s.numText}>{i+1}</Text></View><Text style={s.stepText}>{step}</Text></View>)}<Text style={s.guard}>KYVO Guard obrigatório antes da assinatura ✓</Text></Card>:null}<View style={{height:20}}/></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},content:{padding:16,gap:14},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},close:{color:colors.text,fontSize:34},title:{color:colors.text,fontSize:32,fontWeight:'900'},hero:{color:colors.cyan,fontSize:20,fontWeight:'900'},sub:{color:colors.muted,fontSize:11,lineHeight:17},input:{minHeight:115,borderWidth:1,borderColor:'#303247',borderRadius:16,backgroundColor:'#0B0D14',color:colors.text,padding:14,textAlignVertical:'top',marginBottom:12},summary:{color:colors.muted,fontSize:11,lineHeight:17,marginBottom:8},step:{flexDirection:'row',alignItems:'center',gap:10,paddingVertical:10,borderBottomWidth:1,borderBottomColor:'#202230'},num:{width:28,height:28,borderRadius:14,backgroundColor:'#241538',alignItems:'center',justifyContent:'center'},numText:{color:'#C5A8FF',fontWeight:'900'},stepText:{color:colors.text,fontSize:11,flex:1,lineHeight:16},guard:{color:colors.lime,fontSize:10,fontWeight:'800',marginTop:13}})
