import {router} from 'expo-router';
import {Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {SafeAreaView} from 'react-native-safe-area-context';
import {Card,Pill,SectionTitle} from '@/components/Ui';
import {KyvoLogo} from '@/components/KyvoLogo';
import {colors} from '@/theme/colors';
import {useLocale} from '@/context/LocaleContext';
const currencies=['USD','BRL','EUR','GBP','JPY','KRW','CNY','TRY'];
export default function Settings(){const l=useLocale();return <SafeAreaView style={s.safe}><ScrollView contentContainerStyle={s.content}><View style={s.head}><KyvoLogo/><Pressable onPress={()=>router.back()}><Text style={s.close}>×</Text></Pressable></View><Text style={s.title}>{l.t('settings')}</Text><Text style={s.sub}>{l.t('languageAutoHint')}</Text>
<Card><SectionTitle title={l.t('languageRegion').toUpperCase()}/><Text style={s.caption}>{l.t('currentLanguage')}</Text><View style={s.langs}>{l.supportedLanguages.map(([code,flag,name])=><Pressable key={code} onPress={()=>l.setLanguage(code)} style={[s.lang,l.language===code&&s.langOn]}><Text style={s.flag}>{flag}</Text><Text style={s.langText}>{name}</Text>{l.language===code?<Text style={s.check}>✓</Text>:null}</Pressable>)}</View></Card>
<Card><SectionTitle title={l.t('currency').toUpperCase()}/><View style={s.chips}>{currencies.map(c=><Pressable key={c} onPress={()=>l.setCurrency(c)}><Pill tone={l.currency===c?'green':'purple'}>{c}</Pill></Pressable>)}</View><Text style={s.hint}>{l.t('region')}: {l.region} · {l.currency}</Text></Card>
<Card><SectionTitle title={l.t('preferences')}/>{[[l.t('appearance'),'System / Dark / Light'],[l.t('notifications'),'Push · Security · Social · XP'],[l.t('networks'),'EVM · Solana · Bitcoin · more'],[l.t('privacy'),'Profile · wallet visibility · analytics']].map(([a,b])=><View key={a} style={s.row}><View><Text style={s.rowTitle}>{a}</Text><Text style={s.rowSub}>{b}</Text></View><Text style={s.chev}>›</Text></View>)}</Card>
<Card><SectionTitle title={l.t('walletSecurity')}/>{[l.t('biometrics'),l.t('passkey'),l.t('devices'),l.t('backup'),l.t('antiPhishing')].map(x=><View key={x} style={s.row}><Text style={s.rowTitle}>{x}</Text><Text style={s.chev}>›</Text></View>)}</Card>
<Card><SectionTitle title="KYVO"/><Pressable onPress={()=>router.push('/one')} style={s.row}><View><Text style={s.rowTitle}>KYVO ONE</Text><Text style={s.rowSub}>Intent engine e automação de rotas</Text></View><Text style={s.chev}>›</Text></Pressable><Pressable onPress={()=>router.push('/guard')} style={s.row}><View><Text style={s.rowTitle}>KYVO Guard</Text><Text style={s.rowSub}>Segurança pré-assinatura e simulação</Text></View><Text style={s.chev}>›</Text></Pressable><Pressable onPress={()=>router.push('/pro')} style={s.row}><View><Text style={s.rowTitle}>KYVO Pro</Text><Text style={s.rowSub}>Recursos premium e assinatura</Text></View><Text style={s.chev}>›</Text></Pressable></Card>
<Card><SectionTitle title="INTEGRATIONS"/>{[l.t('spotify'),l.t('dapps'),l.t('fees'),l.t('about')].map(x=><View key={x} style={s.row}><Text style={s.rowTitle}>{x}</Text><Text style={s.chev}>›</Text></View>)}</Card><View style={{height:20}}/></ScrollView></SafeAreaView>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:colors.bg},content:{padding:16,gap:14},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},close:{color:colors.text,fontSize:34},title:{color:colors.text,fontSize:30,fontWeight:'900'},sub:{color:colors.muted,fontSize:11,lineHeight:17},caption:{color:colors.muted,fontSize:10,marginBottom:8},langs:{gap:6},lang:{minHeight:46,borderWidth:1,borderColor:'#242635',backgroundColor:'#0B0D14',borderRadius:13,paddingHorizontal:12,flexDirection:'row',alignItems:'center',gap:10},langOn:{borderColor:colors.violet,backgroundColor:'#171123'},flag:{fontSize:18},langText:{color:colors.text,fontWeight:'700',flex:1},check:{color:colors.lime,fontSize:18,fontWeight:'900'},chips:{flexDirection:'row',gap:8,flexWrap:'wrap'},hint:{color:colors.muted,fontSize:10,marginTop:12},row:{minHeight:51,flexDirection:'row',alignItems:'center',justifyContent:'space-between',borderBottomWidth:1,borderBottomColor:'#202230'},rowTitle:{color:colors.text,fontSize:12,fontWeight:'800'},rowSub:{color:colors.muted,fontSize:9,marginTop:3},chev:{color:colors.muted,fontSize:22}})
