use reqwest::Client;
use serde_json::{json, Value};
use std::{collections::HashSet, fs, path::Path, sync::Arc, time::Duration};
use tokio::sync::RwLock;

const STATE_FILE:&str="/data/explorer-index.json";
const MAX_TRANSACTIONS:usize=10_000;
const MAX_BLOCKS_PER_PASS:u64=25;
const POLL_MS:u64=4_000;

#[derive(Clone)]
pub struct Explorer{state:Arc<RwLock<Value>>,client:Client,rpc_url:String}

fn load_state()->Value{fs::read_to_string(STATE_FILE).ok().and_then(|s|serde_json::from_str(&s).ok()).unwrap_or_else(||json!({"version":1,"genesisHash":null,"lastIndexedBlock":-1,"totalSeen":0,"transactions":[]}))}
fn save_state(v:&Value){if let Some(parent)=Path::new(STATE_FILE).parent(){let _=fs::create_dir_all(parent);}let tmp=format!("{STATE_FILE}.tmp");if fs::write(&tmp,v.to_string()).is_ok(){let _=fs::rename(tmp,STATE_FILE);}}
fn hex_num(v:Option<&Value>)->Option<u64>{let s=v?.as_str()?;u64::from_str_radix(s.trim_start_matches("0x"),16).ok()}
fn lower(v:&Value,key:&str)->String{v.get(key).and_then(Value::as_str).unwrap_or("").to_ascii_lowercase()}

impl Explorer{
 pub fn new(client:Client,rpc_url:String)->Self{let mut s=load_state();if !s.get("transactions").map(Value::is_array).unwrap_or(false){s["transactions"]=json!([]);}Self{state:Arc::new(RwLock::new(s)),client,rpc_url}}
 async fn rpc(&self,method:&str,params:Value)->Result<Value,String>{let r=self.client.post(&self.rpc_url).json(&json!({"jsonrpc":"2.0","id":1,"method":method,"params":params})).send().await.map_err(|e|e.to_string())?;if !r.status().is_success(){return Err(format!("rpc_http_{}",r.status().as_u16()))}let j:Value=r.json().await.map_err(|e|e.to_string())?;if let Some(e)=j.get("error"){return Err(e.get("message").and_then(Value::as_str).unwrap_or("rpc_error").to_string())}Ok(j.get("result").cloned().unwrap_or(Value::Null))}
 async fn ensure_genesis(&self)->Result<(),String>{let block=self.rpc("eth_getBlockByNumber",json!(["0x0",false])).await?;let hash=block.get("hash").and_then(Value::as_str).map(str::to_string);let mut st=self.state.write().await;let old=st.get("genesisHash").and_then(Value::as_str).map(str::to_string);if old.is_some()&&hash.is_some()&&old!=hash{*st=json!({"version":1,"genesisHash":hash,"lastIndexedBlock":-1,"totalSeen":0,"transactions":[]});save_state(&st);}else if old.is_none()&&hash.is_some(){st["genesisHash"]=json!(hash);save_state(&st);}Ok(())}
 async fn index_block(&self,n:u64)->Result<Vec<Value>,String>{let block=self.rpc("eth_getBlockByNumber",json!([format!("0x{n:x}"),true])).await?;if block.is_null(){return Ok(vec![])}let ts=hex_num(block.get("timestamp")).unwrap_or(0);let txs=block.get("transactions").and_then(Value::as_array).cloned().unwrap_or_default();let mut out=Vec::with_capacity(txs.len());for(i,tx)in txs.into_iter().enumerate(){let hash=tx.get("hash").and_then(Value::as_str).unwrap_or("").to_string();let receipt=if hash.is_empty(){Value::Null}else{self.rpc("eth_getTransactionReceipt",json!([hash])).await.unwrap_or(Value::Null)};out.push(json!({"hash":tx.get("hash").cloned().unwrap_or(Value::Null),"blockNumber":hex_num(tx.get("blockNumber")).unwrap_or(n),"blockHash":tx.get("blockHash").cloned().or_else(||block.get("hash").cloned()).unwrap_or(Value::Null),"transactionIndex":hex_num(tx.get("transactionIndex")).unwrap_or(i as u64),"timestamp":ts,"from":tx.get("from").cloned().unwrap_or(Value::Null),"to":tx.get("to").cloned().unwrap_or(Value::Null),"value":tx.get("value").cloned().unwrap_or(json!("0x0")),"nonce":hex_num(tx.get("nonce")),"input":tx.get("input").cloned().unwrap_or(json!("0x")),"gas":tx.get("gas").cloned().unwrap_or(Value::Null),"gasPrice":tx.get("gasPrice").cloned().unwrap_or(Value::Null),"maxFeePerGas":tx.get("maxFeePerGas").cloned().unwrap_or(Value::Null),"maxPriorityFeePerGas":tx.get("maxPriorityFeePerGas").cloned().unwrap_or(Value::Null),"type":tx.get("type").cloned().unwrap_or(Value::Null),"status":receipt.get("status").cloned().unwrap_or(Value::Null),"gasUsed":receipt.get("gasUsed").cloned().unwrap_or(Value::Null),"contractAddress":receipt.get("contractAddress").cloned().unwrap_or(Value::Null)}));}Ok(out)}
 async fn sync_once(&self,pause:bool)->Result<(),String>{if pause{return Ok(())}self.ensure_genesis().await?;let latest=hex_num(Some(&self.rpc("eth_blockNumber",json!([])).await?)).unwrap_or(0);let start={let st=self.state.read().await;let n=st.get("lastIndexedBlock").and_then(Value::as_i64).unwrap_or(-1);if n<0{0}else{n as u64+1}};let end=latest.min(start.saturating_add(MAX_BLOCKS_PER_PASS-1));if start>end{return Ok(())}let mut all=Vec::new();let mut last=start;for n in start..=end{all.extend(self.index_block(n).await?);last=n;}let mut st=self.state.write().await;let arr=st.get_mut("transactions").and_then(Value::as_array_mut).unwrap();let mut seen:HashSet<String>=arr.iter().filter_map(|v|v.get("hash").and_then(Value::as_str).map(|s|s.to_ascii_lowercase())).collect();let mut added=0u64;for tx in all{let key=tx.get("hash").and_then(Value::as_str).unwrap_or("").to_ascii_lowercase();if !key.is_empty()&&seen.insert(key){arr.push(tx);added+=1;}}arr.sort_by(|a,b|{let ab=a.get("blockNumber").and_then(Value::as_u64).unwrap_or(0);let bb=b.get("blockNumber").and_then(Value::as_u64).unwrap_or(0);bb.cmp(&ab).then_with(||b.get("transactionIndex").and_then(Value::as_u64).unwrap_or(0).cmp(&a.get("transactionIndex").and_then(Value::as_u64).unwrap_or(0)))});if arr.len()>MAX_TRANSACTIONS{arr.truncate(MAX_TRANSACTIONS);}let total=st.get("totalSeen").and_then(Value::as_u64).unwrap_or(0)+added;st["totalSeen"]=json!(total);st["lastIndexedBlock"]=json!(last);st["updatedAt"]=json!(std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).unwrap_or_default().as_millis() as u64);save_state(&st);Ok(())}
 pub fn start(self,pause_fn:fn()->bool){tokio::spawn(async move{loop{if let Err(e)=self.sync_once(pause_fn()).await{eprintln!("[zoryq-rust-explorer] index pass failed {e}");}tokio::time::sleep(Duration::from_millis(POLL_MS)).await;}});}
 pub async fn list(&self,page:u64,limit:u64,address:&str,order:&str)->Value{let st=self.state.read().await;let safe_page=page.max(1);let safe_limit=limit.clamp(1,100) as usize;let target=address.to_ascii_lowercase();let mut rows=st.get("transactions").and_then(Value::as_array).cloned().unwrap_or_default();if !target.is_empty(){rows.retain(|tx|lower(tx,"from")==target||lower(tx,"to")==target||lower(tx,"contractAddress")==target);}if order=="asc"{rows.reverse();}let start=(safe_page as usize-1)*safe_limit;json!({"ok":true,"page":safe_page,"limit":safe_limit,"order":if order=="asc"{"asc"}else{"desc"},"totalIndexed":rows.len(),"totalSeen":st.get("totalSeen").and_then(Value::as_u64).unwrap_or(0),"lastIndexedBlock":st.get("lastIndexedBlock").cloned().unwrap_or(json!(-1)),"genesisHash":st.get("genesisHash").cloned().unwrap_or(Value::Null),"transactions":rows.into_iter().skip(start).take(safe_limit).collect::<Vec<_>>()})}
 pub async fn stats(&self,paused:bool)->Value{let st=self.state.read().await;json!({"ok":true,"lastIndexedBlock":st.get("lastIndexedBlock").cloned().unwrap_or(json!(-1)),"totalIndexed":st.get("transactions").and_then(Value::as_array).map(|a|a.len()).unwrap_or(0),"totalSeen":st.get("totalSeen").and_then(Value::as_u64).unwrap_or(0),"genesisHash":st.get("genesisHash").cloned().unwrap_or(Value::Null),"updatedAt":st.get("updatedAt").cloned().unwrap_or(Value::Null),"maxTransactions":MAX_TRANSACTIONS,"maxBlocksPerPass":MAX_BLOCKS_PER_PASS,"pollMs":POLL_MS,"paused":paused,"engine":"rust-native"})}
}
