mod explorer;

use axum::{body::Body, extract::Request, http::{Method, Response, StatusCode}, routing::any, Router};
use bytes::Bytes;
use reqwest::Client;
use serde_json::{json, Value};
use std::{collections::HashMap, env, fs, net::SocketAddr, path::Path, process::Stdio, sync::{Arc, atomic::{AtomicUsize, Ordering}}, time::{Duration, Instant, SystemTime, UNIX_EPOCH}};
use tokio::{process::{Child, Command}, signal, sync::Mutex};

const APP_PORT:u16=8082;
const ADMIN_PORT:u16=8083;
const SOCIAL_PORT:u16=8086;
const WEB_ROOT:&str="/app/web";
const PROTOCOL_ROOT:&str="/app/protocol-out";
const MEMORY_STATUS:&str="/data/zoryq-memory-processes.json";
const PERSISTENCE_STATUS:&str="/data/zoryq-persistence-status.json";
const MAX_BODY:usize=1_000_000;
const MAX_BATCH:usize=50;

#[derive(Clone)] struct Window{started:Instant,count:u32}
#[derive(Clone)] struct State{client:Client,explorer:explorer::Explorer,rpc_windows:Arc<Mutex<HashMap<String,Window>>>,faucet_windows:Arc<Mutex<HashMap<String,Window>>>,rpc_inflight:Arc<AtomicUsize>,faucet_inflight:Arc<AtomicUsize>}

fn json_response(status:StatusCode,value:Value)->Response<Body>{Response::builder().status(status).header("content-type","application/json; charset=utf-8").header("cache-control","no-store").header("access-control-allow-origin","*").header("access-control-allow-headers","content-type").header("access-control-allow-methods","GET,POST,OPTIONS").body(Body::from(value.to_string())).unwrap()}
fn text_response(status:StatusCode,body:Vec<u8>,ctype:&str)->Response<Body>{Response::builder().status(status).header("content-type",ctype).header("cache-control",if ctype.starts_with("text/html"){"no-cache"}else{"public, max-age=300"}).header("access-control-allow-origin","*").body(Body::from(body)).unwrap()}
fn read_json(path:&str)->Option<Value>{fs::read_to_string(path).ok().and_then(|s|serde_json::from_str(&s).ok())}
fn read_num(path:&str)->Option<u64>{let s=fs::read_to_string(path).ok()?;let s=s.trim();if s=="max"{None}else{s.parse().ok()}}
fn memory_percent()->Option<f64>{let cur=read_num("/sys/fs/cgroup/memory.current")? as f64;let lim=read_num("/sys/fs/cgroup/memory.max")? as f64;if lim>0.0{Some(cur/lim*100.0)}else{None}}
fn memory_band()->(&'static str,usize,bool){let p=memory_percent().unwrap_or(0.0);if p>=90.0{("emergency",8,true)}else if p>=85.0{("critical",16,true)}else if p>=80.0{("protect",32,true)}else if p>=70.0{("caution",48,false)}else{("normal",64,false)}}
fn db_ready()->bool{fs::read_dir("/data/reth").ok().and_then(|mut i|i.next()).is_some()}
fn persistence_ready()->bool{let Some(v)=read_json(PERSISTENCE_STATUS) else{return false};v.get("ok").and_then(Value::as_bool)==Some(true)&&v.get("mode").and_then(Value::as_str)==Some("reth-native-db")&&db_ready()}
async fn fetch_json(client:&Client,url:&str)->Option<(StatusCode,Value)>{let r=client.get(url).send().await.ok()?;let status=r.status();let v=r.json().await.ok()?;Some((status,v))}
fn client_ip(req:&Request)->String{req.headers().get("x-real-ip").and_then(|v|v.to_str().ok()).unwrap_or("unknown").trim().to_string()}
async fn allow_window(map:&Mutex<HashMap<String,Window>>,key:&str,span:Duration,limit:u32)->bool{let mut g=map.lock().await;let now=Instant::now();match g.get_mut(key){Some(w) if now.duration_since(w.started)<span=>{if w.count>=limit{return false}w.count+=1;true},_=>{g.insert(key.to_string(),Window{started:now,count:1});true}}}
fn query_param(query:Option<&str>,name:&str)->Option<String>{for pair in query.unwrap_or("").split('&'){let mut it=pair.splitn(2,'=');if it.next()==Some(name){return Some(it.next().unwrap_or("").to_string())}}None}

fn proc_kind(cmd:&str)->&'static str{let s=cmd.to_ascii_lowercase();if s.contains("/reth")||s.starts_with("reth "){"reth"}else if s.contains("public-gateway"){"public-gateway"}else if s.contains("social-service"){"social-service"}else if s.contains("explorer-service"){"explorer-service"}else if s.contains("admin-control"){"admin-control"}else if s.contains("zoryq-gateway"){"rust-gateway"}else{"other"}}
fn proc_budget(kind:&str)->f64{match kind{"reth"=>550.0,"public-gateway"=>90.0,"social-service"=>70.0,"explorer-service"=>70.0,"admin-control"=>50.0,"rust-gateway"=>65.0,_=>80.0}}
fn sample_processes()->Value{let mut rows=Vec::new();if let Ok(entries)=fs::read_dir("/proc"){for e in entries.flatten(){let n=e.file_name();let Some(pid)=n.to_str().and_then(|s|s.parse::<u32>().ok()) else{continue};let status=fs::read_to_string(format!("/proc/{pid}/status")).unwrap_or_default();let cmd=fs::read(format!("/proc/{pid}/cmdline")).ok().map(|b|String::from_utf8_lossy(&b).replace('\0'," ")).unwrap_or_default();let rss_kb=status.lines().find_map(|l|l.strip_prefix("VmRSS:").and_then(|v|v.split_whitespace().next()).and_then(|v|v.parse::<f64>().ok())).unwrap_or(0.0);if rss_kb<=0.0{continue}let kind=proc_kind(&cmd);let rss_mb=(rss_kb/1024.0*100.0).round()/100.0;rows.push(json!({"pid":pid,"kind":kind,"cmdline":cmd,"rssMB":rss_mb,"budgetMB":proc_budget(kind),"overBudget":rss_mb>proc_budget(kind)}));}}rows.sort_by(|a,b|b.get("rssMB").and_then(Value::as_f64).partial_cmp(&a.get("rssMB").and_then(Value::as_f64)).unwrap_or(std::cmp::Ordering::Equal));Value::Array(rows)}
fn write_memory_report(){let processes=sample_processes();let cur=read_num("/sys/fs/cgroup/memory.current");let lim=read_num("/sys/fs/cgroup/memory.max");let percent=match(cur,lim){(Some(c),Some(l)) if l>0=>Some((c as f64/l as f64*10000.0).round()/100.0),_=>None};let alerts=processes.as_array().map(|items|items.iter().filter(|v|v.get("overBudget").and_then(Value::as_bool)==Some(true)).cloned().collect::<Vec<_>>()).unwrap_or_default();let ts=SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_secs();let doc=json!({"ok":true,"source":"rust-native-watchdog","generatedAtUnix":ts,"cgroup":{"currentBytes":cur,"limitBytes":lim,"percent":percent},"alerts":alerts,"processes":processes});let _=fs::create_dir_all("/data");let tmp=format!("{MEMORY_STATUS}.tmp");if fs::write(&tmp,doc.to_string()).is_ok(){let _=fs::rename(tmp,MEMORY_STATUS);}}
async fn native_watchdog(){loop{write_memory_report();tokio::time::sleep(Duration::from_secs(30)).await;}}

async fn health(state:&State)->Response<Body>{let url=format!("http://127.0.0.1:{APP_PORT}/health");let social_url=format!("http://127.0.0.1:{SOCIAL_PORT}/status");let(chain,social)=tokio::join!(fetch_json(&state.client,&url),fetch_json(&state.client,&social_url));let(cs,cv)=chain.unwrap_or((StatusCode::SERVICE_UNAVAILABLE,json!({"error":"chain_unreachable"})));let(ss,sv)=social.unwrap_or((StatusCode::SERVICE_UNAVAILABLE,json!({"error":"social_unreachable"})));let chain_ok=cs.is_success()&&cv.get("ok").and_then(Value::as_bool)==Some(true)&&cv.get("chainId").and_then(Value::as_u64)==Some(5919065)&&cv.get("executionClient").and_then(Value::as_str)==Some("reth");let persist=persistence_ready();let social_ok=ss.is_success()&&sv.get("chainReady").and_then(Value::as_bool)==Some(true);let ok=chain_ok&&persist&&social_ok;let(band,limit,pause)=memory_band();json_response(if ok{StatusCode::OK}else{StatusCode::SERVICE_UNAVAILABLE},json!({"ok":ok,"status":if ok{"healthy"}else{"not_ready"},"chain":cv,"persistence":{"ready":persist,"mode":"reth-native-db"},"product":{"wallet":"ZORYQ Wallet","social":{"ok":social_ok,"status":sv},"explorer":{"engine":"rust-native"},"faucet":true},"governor":{"band":band,"memoryPercent":memory_percent(),"rpcConcurrency":limit,"pauseNonEssential":pause},"memoryWatchdog":"rust-native","release":"infra-v9-rust-explorer"}))}
async fn proxy(state:&State,req:Request,port:u16,path:String)->Response<Body>{let(parts,body)=req.into_parts();let bytes=match axum::body::to_bytes(body,2*MAX_BODY).await{Ok(b)=>b,Err(_)=>return json_response(StatusCode::PAYLOAD_TOO_LARGE,json!({"ok":false,"error":"request_too_large"}))};let url=format!("http://127.0.0.1:{port}{path}");let mut rb=state.client.request(parts.method,url);for(k,v)in parts.headers.iter(){let n=k.as_str();if !matches!(n,"host"|"connection"|"transfer-encoding"|"content-length"|"keep-alive"|"proxy-authenticate"|"proxy-authorization"|"te"|"trailer"|"upgrade"){rb=rb.header(k,v);}}let upstream=match rb.body(bytes).send().await{Ok(r)=>r,Err(e)=>return json_response(StatusCode::SERVICE_UNAVAILABLE,json!({"ok":false,"error":"upstream_unavailable","detail":e.to_string()}))};let status=upstream.status();let headers=upstream.headers().clone();let body=upstream.bytes().await.unwrap_or_else(|_|Bytes::new());let mut b=Response::builder().status(status);for(k,v)in headers.iter(){let n=k.as_str();if !matches!(n,"connection"|"transfer-encoding"|"content-length"|"keep-alive"|"proxy-authenticate"|"proxy-authorization"|"te"|"trailer"|"upgrade"){b=b.header(k,v);}}b.body(Body::from(body)).unwrap()}

fn static_alias(path:&str)->Option<&'static str>{Some(match path{
"/"|"/start"|"/start.html"=>"start.html","/testnet"|"/testnet-lab"|"/testnet-lab.html"=>"testnet-lab.html","/explorer"|"/explorer.html"=>"explorer.html","/leaderboard"|"/leaderboard.html"=>"leaderboard.html","/network-clock"|"/network-clock.html"=>"network-clock.html","/launch-studio"|"/launch-studio.html"=>"launch-studio.html","/node"|"/node.html"=>"node.html","/docs"|"/docs.html"=>"docs.html","/config.js"=>"config.js","/app.js"=>"app.js","/styles.css"=>"styles.css","/x-follow-gate.js"=>"x-follow-gate.js","/genesis-client.js"=>"genesis-client.js",
"/faucet"|"/faucet.html"=>"faucet.html","/swap"|"/swap.html"=>"swap.html","/stake"|"/stake.html"=>"stake.html","/lending"|"/lending.html"=>"lending.html","/developer"|"/developers"|"/developer.html"=>"developer.html","/why"|"/thesis"|"/why-zoryq"|"/why-zoryq.html"=>"why-zoryq.html","/problems"|"/problems.html"=>"problems.html","/ideas"|"/build-ideas"|"/ideas.html"=>"ideas.html","/devkit"|"/devkit.html"=>"devkit.html","/proof"|"/proof-pack"|"/proof.html"=>"proof.html","/launch-project"|"/project-launch"|"/project-launch.html"=>"project-launch.html","/build"|"/quickstart"|"/build.html"=>"build.html","/metrics"|"/traction"|"/metrics.html"=>"metrics.html","/ecosystem"|"/ecosystem.html"=>"ecosystem.html","/builders"|"/challenge"|"/builder-challenge"|"/builder-challenge.html"=>"builder-challenge.html","/investors"|"/investor"|"/investor.html"=>"investor.html","/node-operators"|"/operators"|"/node-operators.html"=>"node-operators.html","/intelligence"|"/genesis-intelligence"|"/intelligence.html"=>"intelligence.html","/admin-control"|"/admin-control.html"=>"admin-control.html","/protocol-launch"|"/protocol-launch.html"=>"protocol-launch.html","/network-maturity"|"/network-maturity.html"=>"network-maturity.html",_=>return None})}
fn ctype(name:&str)->&'static str{if name.ends_with(".json"){"application/json; charset=utf-8"}else if name.ends_with(".js"){"application/javascript; charset=utf-8"}else if name.ends_with(".css"){"text/css; charset=utf-8"}else if name.ends_with(".svg"){"image/svg+xml"}else if name.ends_with(".png"){"image/png"}else if name.ends_with(".ico"){"image/x-icon"}else{"text/html; charset=utf-8"}}
fn serve(root:&str,file:&str)->Response<Body>{let p=Path::new(root).join(file);match fs::read(&p){Ok(mut b)=>{if file.ends_with(".html"){let mut s=String::from_utf8_lossy(&b).to_string();if file=="start.html"&&!s.contains("/genesis-client.js"){s=s.replace("</body>","<script src=\"/genesis-client.js\"></script></body>");}if !s.contains("/i18n.js"){s=s.replace("</body>","<script src=\"/i18n.js\"></script><script src=\"/page-i18n.js\"></script></body>");}b=s.into_bytes();}text_response(StatusCode::OK,b,ctype(file))},Err(_)=>json_response(StatusCode::NOT_FOUND,json!({"ok":false,"error":"not_found"}))}}

async fn handler(axum::extract::State(state):axum::extract::State<State>,req:Request)->Response<Body>{
 let method=req.method().clone();let uri=req.uri().clone();let p=uri.path().to_string();
 if method==Method::OPTIONS{return json_response(StatusCode::NO_CONTENT,json!({}))}
 if method==Method::GET&&(p=="/health"||p=="/ready"){return health(&state).await}
 if method==Method::GET&&p=="/ops/process-memory"{return read_json(MEMORY_STATUS).map(|v|json_response(StatusCode::OK,v)).unwrap_or_else(||json_response(StatusCode::SERVICE_UNAVAILABLE,json!({"ok":false,"error":"native_memory_watchdog_initializing"})))}
 if method==Method::GET&&p=="/ops/memory"{let(band,limit,pause)=memory_band();return json_response(StatusCode::OK,json!({"ok":true,"release":"infra-v9-rust-explorer","memory":{"percent":memory_percent(),"band":band},"rpc":{"inFlight":state.rpc_inflight.load(Ordering::Relaxed),"effectiveConcurrency":limit},"faucet":{"inFlight":state.faucet_inflight.load(Ordering::Relaxed)},"pauseNonEssential":pause}))}
 if method==Method::GET&&p=="/agent/execution-schema.json"{return serve(WEB_ROOT,"zoryq-execution-schema.json")}
 if method==Method::GET&&matches!(p.as_str(),"/social"|"/zoriq"|"/zoriq-social"|"/zoriq-social.html"){return serve(WEB_ROOT,"zoriq-social.html")}
 let pathq=uri.path_and_query().map(|x|x.as_str()).unwrap_or("/").to_string();
 if p.starts_with("/api/social"){let q=pathq.replacen("/api/social","",1);return proxy(&state,req,SOCIAL_PORT,if q.is_empty(){"/".into()}else{q}).await}
 if p.starts_with("/admin/control/"){return proxy(&state,req,ADMIN_PORT,pathq).await}
 if method==Method::GET&&p=="/explorer/stats"{return json_response(StatusCode::OK,state.explorer.stats(memory_band().2).await)}
 if method==Method::GET&&p=="/explorer/transactions"{let page=query_param(uri.query(),"page").and_then(|v|v.parse().ok()).unwrap_or(1);let limit=query_param(uri.query(),"limit").and_then(|v|v.parse().ok()).unwrap_or(50);let address=query_param(uri.query(),"address").unwrap_or_default();let order=query_param(uri.query(),"order").unwrap_or_else(||"desc".into());return json_response(StatusCode::OK,state.explorer.list(page,limit,&address,&order).await)}
 if method==Method::GET&&p.starts_with("/protocol-artifacts/"){let f=match p.as_str(){"/protocol-artifacts/dexV1.json"=>Some("ZoryqDexV1.sol/ZoryqDexV1.json"),"/protocol-artifacts/lending.json"=>Some("ZoryqLendingLab.sol/ZoryqLendingLab.json"),"/protocol-artifacts/projectRegistry.json"=>Some("ZoryqProjectRegistry.sol/ZoryqProjectRegistry.json"),_=>None};if let Some(f)=f{return serve(PROTOCOL_ROOT,f)}}
 if method==Method::GET||method==Method::HEAD{if let Some(f)=static_alias(&p){return serve(WEB_ROOT,f)}}
 let is_rpc=method==Method::POST&&(p=="/rpc"||p=="/");let is_faucet=method==Method::POST&&p=="/faucet";
 if is_rpc{let ip=client_ip(&req);if !allow_window(&state.rpc_windows,&ip,Duration::from_secs(60),600).await{return json_response(StatusCode::TOO_MANY_REQUESTS,json!({"jsonrpc":"2.0","id":null,"error":{"code":-32005,"message":"RPC rate limit exceeded"}}))}let(_,limit,_)=memory_band();let now=state.rpc_inflight.fetch_add(1,Ordering::SeqCst)+1;if now>limit{state.rpc_inflight.fetch_sub(1,Ordering::SeqCst);return json_response(StatusCode::SERVICE_UNAVAILABLE,json!({"jsonrpc":"2.0","id":null,"error":{"code":-32005,"message":"RPC temporarily saturated"}}))}let(parts,body)=req.into_parts();let bytes=match axum::body::to_bytes(body,MAX_BODY).await{Ok(b)=>b,Err(_)=>{state.rpc_inflight.fetch_sub(1,Ordering::SeqCst);return json_response(StatusCode::PAYLOAD_TOO_LARGE,json!({"ok":false,"error":"request_too_large"}))}};if let Ok(v)=serde_json::from_slice::<Value>(&bytes){if v.as_array().map(|a|a.len()>MAX_BATCH).unwrap_or(false){state.rpc_inflight.fetch_sub(1,Ordering::SeqCst);return json_response(StatusCode::PAYLOAD_TOO_LARGE,json!({"jsonrpc":"2.0","id":null,"error":{"code":-32600,"message":"JSON-RPC batch limit is 50"}}))}}else{state.rpc_inflight.fetch_sub(1,Ordering::SeqCst);return json_response(StatusCode::BAD_REQUEST,json!({"jsonrpc":"2.0","id":null,"error":{"code":-32700,"message":"Parse error"}}))}let rebuilt=Request::from_parts(parts,Body::from(bytes));let out=proxy(&state,rebuilt,APP_PORT,pathq).await;state.rpc_inflight.fetch_sub(1,Ordering::SeqCst);return out}
 if is_faucet{let ip=client_ip(&req);if !allow_window(&state.faucet_windows,&ip,Duration::from_secs(3600),5).await{return json_response(StatusCode::TOO_MANY_REQUESTS,json!({"ok":false,"error":"faucet_ip_rate_limit"}))}let(_,_,protect)=memory_band();let limit=if protect{1}else{8};let now=state.faucet_inflight.fetch_add(1,Ordering::SeqCst)+1;if now>limit{state.faucet_inflight.fetch_sub(1,Ordering::SeqCst);return json_response(StatusCode::SERVICE_UNAVAILABLE,json!({"ok":false,"error":"faucet_temporarily_saturated"}))}let out=proxy(&state,req,APP_PORT,pathq).await;state.faucet_inflight.fetch_sub(1,Ordering::SeqCst);return out}
 proxy(&state,req,APP_PORT,pathq).await
}

fn spawn_node(name:&str,args:&[&str],envs:&[(&str,String)])->Child{let mut c=Command::new("/usr/local/bin/node");c.args(args).stdin(Stdio::null()).stdout(Stdio::inherit()).stderr(Stdio::inherit());for(k,v)in envs{c.env(k,v);}let child=c.spawn().unwrap_or_else(|e|panic!("failed to spawn {name}: {e}"));println!("[zoryq-rust] spawned {name}");child}

#[tokio::main(flavor="multi_thread",worker_threads=2)]
async fn main(){
 let port=env::var("PORT").ok().and_then(|v|v.parse().ok()).unwrap_or(8080u16);
 let chain_spec=env::var("ZORYQ_RETH_CHAIN_SPEC").unwrap_or_else(|_|"/data/zoryq-reth-effective-genesis.json".into());
 let allow_reset=if Path::new("/data/zoryq-reth-migration.json").exists(){"true".into()}else{env::var("ZORYQ_ALLOW_RETH_GENESIS_RESET").unwrap_or_else(|_|"false".into())};
 let public=spawn_node("public-gateway",&["--max-old-space-size=128","public-gateway.mjs"],&[("PORT",APP_PORT.to_string()),("ZORYQ_RETH_CHAIN_SPEC",chain_spec),("ZORYQ_ALLOW_RETH_GENESIS_RESET",allow_reset),("NODE_OPTIONS","--max-old-space-size=128".into())]);
 let admin=spawn_node("admin",&["--max-old-space-size=64","admin-control.mjs"],&[("PORT",ADMIN_PORT.to_string()),("NODE_OPTIONS","--max-old-space-size=64".into())]);
 let social=spawn_node("social",&["--max-old-space-size=96","social-service.mjs"],&[("PORT",SOCIAL_PORT.to_string()),("ZORYQ_CHAIN_BASE",format!("http://127.0.0.1:{APP_PORT}")),("NODE_OPTIONS","--max-old-space-size=96".into())]);
 let children=Arc::new(Mutex::new(vec![public,admin,social]));
 let monitor=children.clone();tokio::spawn(async move{loop{tokio::time::sleep(Duration::from_secs(2)).await;let mut g=monitor.lock().await;for c in g.iter_mut(){if let Ok(Some(status))=c.try_wait(){eprintln!("[zoryq-rust] child exited: {status}");std::process::exit(1)}}}});
 tokio::spawn(native_watchdog());
 let client=Client::builder().timeout(Duration::from_secs(20)).build().unwrap();
 let explorer=explorer::Explorer::new(client.clone(),format!("http://127.0.0.1:{APP_PORT}/rpc"));explorer.clone().start(||memory_band().2);
 let state=State{client,explorer,rpc_windows:Arc::new(Mutex::new(HashMap::new())),faucet_windows:Arc::new(Mutex::new(HashMap::new())),rpc_inflight:Arc::new(AtomicUsize::new(0)),faucet_inflight:Arc::new(AtomicUsize::new(0))};
 let app=Router::new().fallback(any(handler)).with_state(state);
 println!("[zoryq-rust] native explorer active; app={APP_PORT}; admin={ADMIN_PORT}; watchdog=rust-native; release=infra-v9-rust-explorer");
 let listener=tokio::net::TcpListener::bind(SocketAddr::from(([0,0,0,0],port))).await.expect("bind");
 let shutdown_children=children.clone();axum::serve(listener,app).with_graceful_shutdown(async move{let _=signal::ctrl_c().await;let mut g=shutdown_children.lock().await;for c in g.iter_mut(){let _=c.start_kill();}}).await.expect("serve")
}
