use k256::ecdsa::{RecoveryId,Signature,VerifyingKey};
use rand::{rngs::OsRng,RngCore};
use serde_json::{json,Value};
use sha3::{Digest,Keccak256};
use std::{collections::{HashMap,HashSet},env,fs,sync::OnceLock,time::{Duration,Instant,SystemTime,UNIX_EPOCH}};
use tokio::sync::Mutex;

const CHALLENGE_TTL:Duration=Duration::from_secs(600);
#[derive(Clone)]struct Challenge{id:String,address:String,action:String,payload:Value,message:String,expires_at:u64,created:Instant}
static CHALLENGES:OnceLock<Mutex<HashMap<String,Challenge>>>=OnceLock::new();
fn challenges()->&'static Mutex<HashMap<String,Challenge>>{CHALLENGES.get_or_init(||Mutex::new(HashMap::new()))}
#[derive(Default)]
struct Model{profiles:HashMap<String,Value>,usernames:HashMap<String,String>,posts:HashMap<String,Value>,likes:HashMap<String,HashSet<String>>,reposts:HashMap<String,HashSet<String>>,bookmarks:HashMap<String,HashSet<String>>,follows:HashMap<String,HashSet<String>>,anchored:u64}
fn store_file()->String{env::var("ZORYQ_SOCIAL_STORE").unwrap_or_else(|_|"/data/zoryq-social-events.ndjson".into())}
fn norm(s:&str)->String{s.trim().to_ascii_lowercase()}
fn as_str<'a>(v:&'a Value,k:&str)->&'a str{v.get(k).and_then(Value::as_str).unwrap_or("")}
fn hex_encode(bytes:&[u8])->String{bytes.iter().map(|b|format!("{b:02x}")).collect()}
fn hex_decode(s:&str)->Result<Vec<u8>,String>{let s=s.strip_prefix("0x").unwrap_or(s);if s.len()%2!=0{return Err("invalid_hex".into())}let mut out=Vec::with_capacity(s.len()/2);for i in (0..s.len()).step_by(2){out.push(u8::from_str_radix(&s[i..i+2],16).map_err(|_|"invalid_hex")?)}Ok(out)}
fn checksum_address(lower:&str)->String{let raw=lower.trim_start_matches("0x").to_ascii_lowercase();let mut h=Keccak256::new();h.update(raw.as_bytes());let digest=hex_encode(&h.finalize());let mut out=String::from("0x");for(i,c)in raw.chars().enumerate(){if c.is_ascii_alphabetic()&&u8::from_str_radix(&digest[i..i+1],16).unwrap_or(0)>=8{out.push(c.to_ascii_uppercase())}else{out.push(c)}}out}
fn normalize_address(v:&str)->Option<String>{let s=v.trim().to_ascii_lowercase();if s.len()==42&&s.starts_with("0x")&&s[2..].bytes().all(|b|b.is_ascii_hexdigit()){Some(checksum_address(&s))}else{None}}
fn canonical(v:&Value)->String{match v{Value::Object(m)=>{let mut keys=m.keys().collect::<Vec<_>>();keys.sort();format!("{{{}}}",keys.into_iter().map(|k|format!("{}:{}",serde_json::to_string(k).unwrap(),canonical(&m[k]))).collect::<Vec<_>>().join(","))},Value::Array(a)=>format!("[{}]",a.iter().map(canonical).collect::<Vec<_>>().join(",")),_=>serde_json::to_string(v).unwrap_or_else(|_|"null".into())}}
fn payload_hash(payload:&Value)->String{let mut h=Keccak256::new();h.update(canonical(payload).as_bytes());format!("0x{}",hex_encode(&h.finalize()))}
fn uuid_v4()->String{let mut b=[0u8;16];OsRng.fill_bytes(&mut b);b[6]=(b[6]&0x0f)|0x40;b[8]=(b[8]&0x3f)|0x80;format!("{}-{}-{}-{}-{}",hex_encode(&b[0..4]),hex_encode(&b[4..6]),hex_encode(&b[6..8]),hex_encode(&b[8..10]),hex_encode(&b[10..16]))}
fn ethereum_message_hash(message:&str)->[u8;32]{let prefix=format!("\x19Ethereum Signed Message:\n{}",message.len());let mut h=Keccak256::new();h.update(prefix.as_bytes());h.update(message.as_bytes());let out=h.finalize();let mut r=[0u8;32];r.copy_from_slice(&out);r}
fn recover_address(message:&str,signature:&str)->Result<String,String>{let b=hex_decode(signature)?;if b.len()!=65{return Err("invalid_signature".into())}let sig=Signature::try_from(&b[..64]).map_err(|_|"invalid_signature")?;let v=match b[64]{27|28=>b[64]-27,0|1=>b[64],_=>return Err("invalid_signature".into())};let rid=RecoveryId::try_from(v).map_err(|_|"invalid_signature")?;let key=VerifyingKey::recover_from_prehash(&ethereum_message_hash(message),&sig,rid).map_err(|_|"invalid_signature")?;let p=key.to_encoded_point(false);let mut h=Keccak256::new();h.update(&p.as_bytes()[1..]);let out=h.finalize();Ok(checksum_address(&format!("0x{}",hex_encode(&out[12..]))))}
fn trim_limit(v:&Value,max:usize)->String{v.as_str().unwrap_or("").trim().chars().take(max).collect()}
fn https_url(v:&Value)->String{let s=v.as_str().unwrap_or("").trim();if s.len()>500||!s.starts_with("https://"){String::new()}else{s.to_string()}}
fn validate_payload(action:&str,payload:&Value,address:&str)->Result<Value,String>{let m=load();match action{
"profile"=>{let username=trim_limit(payload.get("username").unwrap_or(&Value::Null),24).to_ascii_lowercase();if username.len()<3||!username.bytes().all(|b|b.is_ascii_lowercase()||b.is_ascii_digit()||b==b'_'){return Err("invalid_username".into())}let display=trim_limit(payload.get("displayName").unwrap_or(&Value::Null),40);if display.is_empty(){return Err("display_name_required".into())}if let Some(owner)=m.usernames.get(&username){if owner!=&norm(address){return Err("username_taken".into())}}Ok(json!({"username":username,"displayName":display,"bio":trim_limit(payload.get("bio").unwrap_or(&Value::Null),160),"avatarUrl":https_url(payload.get("avatarUrl").unwrap_or(&Value::Null))}))},
"post"=>{let body=trim_limit(payload.get("text").unwrap_or(&Value::Null),500);if body.is_empty(){return Err("post_text_required".into())}let reply=payload.get("replyTo").and_then(Value::as_str).map(str::to_string);if let Some(r)=reply.as_ref(){if !m.posts.contains_key(r){return Err("reply_target_not_found".into())}}Ok(json!({"text":body,"mediaUrl":https_url(payload.get("mediaUrl").unwrap_or(&Value::Null)),"replyTo":reply}))},
"like"|"repost"|"bookmark"=>{let id=as_str(payload,"postId");if !m.posts.contains_key(id){return Err("post_not_found".into())}Ok(json!({"postId":id}))},
"follow"=>{let target=normalize_address(as_str(payload,"target")).ok_or_else(||"invalid_target".to_string())?;if norm(&target)==norm(address){return Err("cannot_follow_self".into())}Ok(json!({"target":target}))},_=>Err("unsupported_social_action".into())}}
fn apply(m:&mut Model,e:&Value){let typ=as_str(e,"type");let address=norm(as_str(e,"address"));match typ{"profile"=>{let p=e.get("payload").cloned().unwrap_or_else(||json!({}));let username=norm(as_str(&p,"username"));if let Some(old)=m.profiles.get(&address){if let Some(u)=old.get("username").and_then(Value::as_str){m.usernames.remove(&norm(u));}}let item=json!({"address":as_str(e,"address"),"username":username,"displayName":as_str(&p,"displayName"),"bio":as_str(&p,"bio"),"avatarUrl":as_str(&p,"avatarUrl"),"createdAt":m.profiles.get(&address).and_then(|x|x.get("createdAt")).cloned().unwrap_or_else(||e.get("createdAt").cloned().unwrap_or(Value::Null)),"updatedAt":e.get("createdAt").cloned().unwrap_or(Value::Null),"anchorTxHash":e.get("anchorTxHash").cloned().unwrap_or(Value::Null)});m.usernames.insert(username,address.clone());m.profiles.insert(address,item);},"post"=>{if let Some(id)=e.get("id").and_then(Value::as_str){let p=e.get("payload").cloned().unwrap_or_else(||json!({}));m.posts.insert(id.to_string(),json!({"id":id,"address":as_str(e,"address"),"text":as_str(&p,"text"),"mediaUrl":as_str(&p,"mediaUrl"),"replyTo":p.get("replyTo").cloned().unwrap_or(Value::Null),"createdAt":e.get("createdAt").cloned().unwrap_or(Value::Null),"anchorTxHash":e.get("anchorTxHash").cloned().unwrap_or(Value::Null)}));}},"like"|"repost"=>{if let Some(pid)=e.get("postId").and_then(Value::as_str){let map=if typ=="like"{&mut m.likes}else{&mut m.reposts};let set=map.entry(pid.to_string()).or_default();if e.get("active").and_then(Value::as_bool).unwrap_or(false){set.insert(address);}else{set.remove(&address);}}},"bookmark"=>{if let Some(pid)=e.get("postId").and_then(Value::as_str){let set=m.bookmarks.entry(address.clone()).or_default();if e.get("active").and_then(Value::as_bool).unwrap_or(false){set.insert(pid.to_string());}else{set.remove(pid);}}},"follow"=>{let target=norm(as_str(e,"target"));let set=m.follows.entry(address).or_default();if e.get("active").and_then(Value::as_bool).unwrap_or(false){set.insert(target);}else{set.remove(&target);}},"anchor"=>m.anchored+=1,_=>{}}}
fn load()->Model{let mut m=Model::default();if let Ok(s)=fs::read_to_string(store_file()){for line in s.lines(){if let Ok(v)=serde_json::from_str::<Value>(line){apply(&mut m,&v);}}}m}
fn profile_view(m:&Model,address:&str,viewer:&str)->Option<Value>{let a=norm(address);let p=m.profiles.get(&a)?.clone();let followers=m.follows.values().filter(|s|s.contains(&a)).count();let following=m.follows.get(&a).map(HashSet::len).unwrap_or(0);let posts=m.posts.values().filter(|x|norm(as_str(x,"address"))==a).count();let viewer_following=!viewer.is_empty()&&m.follows.get(&norm(viewer)).map(|s|s.contains(&a)).unwrap_or(false);let mut o=p.as_object()?.clone();o.insert("followers".into(),json!(followers));o.insert("following".into(),json!(following));o.insert("posts".into(),json!(posts));o.insert("viewerFollowing".into(),json!(viewer_following));Some(Value::Object(o))}
fn post_view(m:&Model,p:&Value,viewer:&str)->Value{let id=as_str(p,"id");let address=as_str(p,"address");let likes=m.likes.get(id).map(HashSet::len).unwrap_or(0);let reposts=m.reposts.get(id).map(HashSet::len).unwrap_or(0);let replies=m.posts.values().filter(|x|x.get("replyTo").and_then(Value::as_str)==Some(id)).count();let v=norm(viewer);let liked=!v.is_empty()&&m.likes.get(id).map(|s|s.contains(&v)).unwrap_or(false);let reposted=!v.is_empty()&&m.reposts.get(id).map(|s|s.contains(&v)).unwrap_or(false);let saved=!v.is_empty()&&m.bookmarks.get(&v).map(|s|s.contains(id)).unwrap_or(false);let author=profile_view(m,address,viewer).unwrap_or_else(||json!({"address":address,"username":address,"displayName":address,"bio":"","avatarUrl":""}));let mut o=p.as_object().cloned().unwrap_or_default();o.insert("author".into(),author);o.insert("likes".into(),json!(likes));o.insert("reposts".into(),json!(reposts));o.insert("replies".into(),json!(replies));o.insert("liked".into(),json!(liked));o.insert("reposted".into(),json!(reposted));o.insert("saved".into(),json!(saved));Value::Object(o)}
pub fn status(chain_ready:bool,block:Option<u64>)->Value{let m=load();json!({"ok":chain_ready,"service":"zoryq-social","engine":"rust-native-read","chainId":5919065,"chainReady":chain_ready,"block":block,"profiles":m.profiles.len(),"posts":m.posts.len(),"anchoredActions":m.anchored,"anchorEnabled":env::var("ZORYQ_SOCIAL_ANCHOR").unwrap_or_else(|_|"true".into()).to_ascii_lowercase()!="false","store":"append-only-event-log"})}
pub fn feed(viewer:&str,limit:usize,before:u64)->Value{let m=load();let mut rows=m.posts.values().filter(|p|p.get("createdAt").and_then(Value::as_u64).unwrap_or(0)<before).cloned().collect::<Vec<_>>();rows.sort_by_key(|p|std::cmp::Reverse(p.get("createdAt").and_then(Value::as_u64).unwrap_or(0)));rows.truncate(limit.clamp(1,50));let out=rows.iter().map(|p|post_view(&m,p,viewer)).collect::<Vec<_>>();let next=out.last().and_then(|p|p.get("createdAt")).cloned().unwrap_or(Value::Null);json!({"ok":true,"posts":out,"nextBefore":next})}
pub fn profile(address:&str,username:&str,viewer:&str)->Result<Value,Value>{let m=load();let resolved=if !address.is_empty(){norm(address)}else if !username.is_empty(){m.usernames.get(&norm(username)).cloned().unwrap_or_default()}else{String::new()};let Some(p)=profile_view(&m,&resolved,viewer) else{return Err(json!({"ok":false,"error":"profile_not_found"}))};let mut posts=m.posts.values().filter(|x|norm(as_str(x,"address"))==resolved).cloned().collect::<Vec<_>>();posts.sort_by_key(|p|std::cmp::Reverse(p.get("createdAt").and_then(Value::as_u64).unwrap_or(0)));posts.truncate(30);Ok(json!({"ok":true,"profile":p,"posts":posts.iter().map(|x|post_view(&m,x,viewer)).collect::<Vec<_>>() }))}
pub fn bookmarks(viewer:&str)->Result<Value,Value>{let v=norm(viewer);if v.is_empty(){return Err(json!({"ok":false,"error":"viewer_required"}))}let m=load();let ids=m.bookmarks.get(&v).cloned().unwrap_or_default();let mut rows=m.posts.values().filter(|p|ids.contains(as_str(p,"id"))).cloned().collect::<Vec<_>>();rows.sort_by_key(|p|std::cmp::Reverse(p.get("createdAt").and_then(Value::as_u64).unwrap_or(0)));Ok(json!({"ok":true,"posts":rows.iter().map(|x|post_view(&m,x,viewer)).collect::<Vec<_>>() }))}
pub async fn challenge(address_raw:&str,action:&str,payload:&Value)->Result<Value,(u16,Value)>{let address=normalize_address(address_raw).ok_or((400,json!({"ok":false,"error":"invalid_address"})))?;let payload=validate_payload(action,payload,&address).map_err(|e|(400,json!({"ok":false,"error":e})))?;let id=uuid_v4();let expires=SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_millis() as u64+600_000;let hash=payload_hash(&payload);let message=format!("ZORYQ Social Authorization\nChain ID: 5919065\nWallet: {address}\nAction: {action}\nChallenge: {id}\nPayload Hash: {hash}\nExpires: {expires}");let c=Challenge{id:id.clone(),address:address.clone(),action:action.to_string(),payload:payload.clone(),message:message.clone(),expires_at:expires,created:Instant::now()};let mut g=challenges().lock().await;g.retain(|_,c|c.created.elapsed()<CHALLENGE_TTL);g.insert(id.clone(),c);Ok(json!({"ok":true,"challengeId":id,"message":message,"expiresAt":expires,"payloadHash":hash,"chainId":5919065}))}
pub async fn verify_challenge(id:&str,signature:&str)->Result<(String,String,Value),(u16,Value)>{let mut g=challenges().lock().await;g.retain(|_,c|c.created.elapsed()<CHALLENGE_TTL);let Some(c)=g.get(id).cloned() else{return Err((401,json!({"ok":false,"error":"challenge_not_found_or_expired"})))};if SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_millis() as u64>=c.expires_at{g.remove(id);return Err((401,json!({"ok":false,"error":"challenge_not_found_or_expired"})))}let signer=recover_address(&c.message,signature).map_err(|_|(401,json!({"ok":false,"error":"invalid_signature"})))?;if norm(&signer)!=norm(&c.address){return Err((401,json!({"ok":false,"error":"signature_wallet_mismatch"})))}g.remove(id);Ok((c.address,c.action,c.payload))}
