use serde_json::{json,Value};
use std::{collections::{HashMap,HashSet},env,fs};

#[derive(Default)]
struct Model{
 profiles:HashMap<String,Value>,
 usernames:HashMap<String,String>,
 posts:HashMap<String,Value>,
 likes:HashMap<String,HashSet<String>>,
 reposts:HashMap<String,HashSet<String>>,
 bookmarks:HashMap<String,HashSet<String>>,
 follows:HashMap<String,HashSet<String>>,
 anchored:u64,
}
fn store_file()->String{env::var("ZORYQ_SOCIAL_STORE").unwrap_or_else(|_|"/data/zoryq-social-events.ndjson".into())}
fn norm(s:&str)->String{s.trim().to_ascii_lowercase()}
fn as_str<'a>(v:&'a Value,k:&str)->&'a str{v.get(k).and_then(Value::as_str).unwrap_or("")}
fn apply(m:&mut Model,e:&Value){let typ=as_str(e,"type");let address=norm(as_str(e,"address"));match typ{
"profile"=>{let p=e.get("payload").cloned().unwrap_or_else(||json!({}));let username=norm(as_str(&p,"username"));if let Some(old)=m.profiles.get(&address){if let Some(u)=old.get("username").and_then(Value::as_str){m.usernames.remove(&norm(u));}}
 let item=json!({"address":as_str(e,"address"),"username":username,"displayName":as_str(&p,"displayName"),"bio":as_str(&p,"bio"),"avatarUrl":as_str(&p,"avatarUrl"),"createdAt":m.profiles.get(&address).and_then(|x|x.get("createdAt")).cloned().unwrap_or_else(||e.get("createdAt").cloned().unwrap_or(Value::Null)),"updatedAt":e.get("createdAt").cloned().unwrap_or(Value::Null),"anchorTxHash":e.get("anchorTxHash").cloned().unwrap_or(Value::Null)});m.usernames.insert(username,address.clone());m.profiles.insert(address,item);},
"post"=>{if let Some(id)=e.get("id").and_then(Value::as_str){let p=e.get("payload").cloned().unwrap_or_else(||json!({}));m.posts.insert(id.to_string(),json!({"id":id,"address":as_str(e,"address"),"text":as_str(&p,"text"),"mediaUrl":as_str(&p,"mediaUrl"),"replyTo":p.get("replyTo").cloned().unwrap_or(Value::Null),"createdAt":e.get("createdAt").cloned().unwrap_or(Value::Null),"anchorTxHash":e.get("anchorTxHash").cloned().unwrap_or(Value::Null)}));}},
"like"|"repost"=>{if let Some(pid)=e.get("postId").and_then(Value::as_str){let map=if typ=="like"{&mut m.likes}else{&mut m.reposts};let set=map.entry(pid.to_string()).or_default();if e.get("active").and_then(Value::as_bool).unwrap_or(false){set.insert(address)}else{set.remove(&address);}}},
"bookmark"=>{if let Some(pid)=e.get("postId").and_then(Value::as_str){let set=m.bookmarks.entry(address.clone()).or_default();if e.get("active").and_then(Value::as_bool).unwrap_or(false){set.insert(pid.to_string());}else{set.remove(pid);}}},
"follow"=>{let target=norm(as_str(e,"target"));let set=m.follows.entry(address).or_default();if e.get("active").and_then(Value::as_bool).unwrap_or(false){set.insert(target);}else{set.remove(&target);}},
"anchor"=>m.anchored+=1,_=>{}}
}
fn load()->Model{let mut m=Model::default();if let Ok(s)=fs::read_to_string(store_file()){for line in s.lines(){if let Ok(v)=serde_json::from_str::<Value>(line){apply(&mut m,&v);}}}m}
fn profile_view(m:&Model,address:&str,viewer:&str)->Option<Value>{let a=norm(address);let p=m.profiles.get(&a)?.clone();let followers=m.follows.values().filter(|s|s.contains(&a)).count();let following=m.follows.get(&a).map(HashSet::len).unwrap_or(0);let posts=m.posts.values().filter(|x|norm(as_str(x,"address"))==a).count();let viewer_following=!viewer.is_empty()&&m.follows.get(&norm(viewer)).map(|s|s.contains(&a)).unwrap_or(false);let mut o=p.as_object()?.clone();o.insert("followers".into(),json!(followers));o.insert("following".into(),json!(following));o.insert("posts".into(),json!(posts));o.insert("viewerFollowing".into(),json!(viewer_following));Some(Value::Object(o))}
fn post_view(m:&Model,p:&Value,viewer:&str)->Value{let id=as_str(p,"id");let address=as_str(p,"address");let likes=m.likes.get(id).map(HashSet::len).unwrap_or(0);let reposts=m.reposts.get(id).map(HashSet::len).unwrap_or(0);let replies=m.posts.values().filter(|x|x.get("replyTo").and_then(Value::as_str)==Some(id)).count();let v=norm(viewer);let liked=!v.is_empty()&&m.likes.get(id).map(|s|s.contains(&v)).unwrap_or(false);let reposted=!v.is_empty()&&m.reposts.get(id).map(|s|s.contains(&v)).unwrap_or(false);let saved=!v.is_empty()&&m.bookmarks.get(&v).map(|s|s.contains(id)).unwrap_or(false);let author=profile_view(m,address,viewer).unwrap_or_else(||json!({"address":address,"username":address,"displayName":address,"bio":"","avatarUrl":""}));let mut o=p.as_object().cloned().unwrap_or_default();o.insert("author".into(),author);o.insert("likes".into(),json!(likes));o.insert("reposts".into(),json!(reposts));o.insert("replies".into(),json!(replies));o.insert("liked".into(),json!(liked));o.insert("reposted".into(),json!(reposted));o.insert("saved".into(),json!(saved));Value::Object(o)}
pub fn status(chain_ready:bool,block:Option<u64>)->Value{let m=load();json!({"ok":chain_ready,"service":"zoryq-social","engine":"rust-native-read","chainId":5919065,"chainReady":chain_ready,"block":block,"profiles":m.profiles.len(),"posts":m.posts.len(),"anchoredActions":m.anchored,"anchorEnabled":env::var("ZORYQ_SOCIAL_ANCHOR").unwrap_or_else(|_|"true".into()).to_ascii_lowercase()!="false","store":"append-only-event-log"})}
pub fn feed(viewer:&str,limit:usize,before:u64)->Value{let m=load();let mut rows=m.posts.values().filter(|p|p.get("createdAt").and_then(Value::as_u64).unwrap_or(0)<before).cloned().collect::<Vec<_>>();rows.sort_by_key(|p|std::cmp::Reverse(p.get("createdAt").and_then(Value::as_u64).unwrap_or(0)));rows.truncate(limit.clamp(1,50));let out=rows.iter().map(|p|post_view(&m,p,viewer)).collect::<Vec<_>>();let next=out.last().and_then(|p|p.get("createdAt")).cloned().unwrap_or(Value::Null);json!({"ok":true,"posts":out,"nextBefore":next})}
pub fn profile(address:&str,username:&str,viewer:&str)->Result<Value,Value>{let m=load();let resolved=if !address.is_empty(){norm(address)}else if !username.is_empty(){m.usernames.get(&norm(username)).cloned().unwrap_or_default()}else{String::new()};let Some(p)=profile_view(&m,&resolved,viewer) else{return Err(json!({"ok":false,"error":"profile_not_found"}))};let mut posts=m.posts.values().filter(|x|norm(as_str(x,"address"))==resolved).cloned().collect::<Vec<_>>();posts.sort_by_key(|p|std::cmp::Reverse(p.get("createdAt").and_then(Value::as_u64).unwrap_or(0)));posts.truncate(30);Ok(json!({"ok":true,"profile":p,"posts":posts.iter().map(|x|post_view(&m,x,viewer)).collect::<Vec<_>>() }))}
pub fn bookmarks(viewer:&str)->Result<Value,Value>{let v=norm(viewer);if v.is_empty(){return Err(json!({"ok":false,"error":"viewer_required"}))}let m=load();let ids=m.bookmarks.get(&v).cloned().unwrap_or_default();let mut rows=m.posts.values().filter(|p|ids.contains(as_str(p,"id"))).cloned().collect::<Vec<_>>();rows.sort_by_key(|p|std::cmp::Reverse(p.get("createdAt").and_then(Value::as_u64).unwrap_or(0)));Ok(json!({"ok":true,"posts":rows.iter().map(|x|post_view(&m,x,viewer)).collect::<Vec<_>>() }))}
