import http from 'node:http';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import crypto from 'node:crypto';
import { spawn } from 'node:child_process';

const PORT = Number(process.env.PORT || 8080);
const TEMPLATE = '/app/template';
const JOB_ROOT = '/data/jobs';
const ORIGIN = process.env.ZORYQ_FACTORY_ORIGIN || 'https://zoryq-evm-node-live-production.up.railway.app';
const KEYSTORE_B64 = String(process.env.ZORYQ_ANDROID_KEYSTORE_B64 || '');
const KEY_ALIAS = String(process.env.ZORYQ_ANDROID_KEY_ALIAS || '');
const KEYSTORE_PASSWORD = String(process.env.ZORYQ_ANDROID_KEYSTORE_PASSWORD || '');
const KEY_PASSWORD = String(process.env.ZORYQ_ANDROID_KEY_PASSWORD || '');
const MAX_BODY = 1_000_000;
const jobs = new Map();
const rate = new Map();
let active = false;

fs.mkdirSync(JOB_ROOT, { recursive: true, mode: 0o700 });
const keystore = '/data/zoryq-factory-release.jks';
if (KEYSTORE_B64 && !fs.existsSync(keystore)) fs.writeFileSync(keystore, Buffer.from(KEYSTORE_B64, 'base64'), { mode: 0o600 });

function cors(req, res) { const origin=String(req.headers.origin||''); if(origin===ORIGIN){res.setHeader('access-control-allow-origin',ORIGIN);res.setHeader('vary','Origin')} res.setHeader('access-control-allow-methods','GET,POST,OPTIONS');res.setHeader('access-control-allow-headers','content-type'); }
function send(req,res,status,data){cors(req,res);res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store'});res.end(JSON.stringify(data))}
function clientIp(req){return String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0].trim()}
function allow(ip){const now=Date.now(),span=60*60*1000,row=rate.get(ip)||[],fresh=row.filter(t=>now-t<span);if(fresh.length>=3)return false;fresh.push(now);rate.set(ip,fresh);return true}
async function readJson(req){const chunks=[];let total=0;for await(const c of req){total+=c.length;if(total>MAX_BODY)throw Error('request_too_large');chunks.push(c)}return JSON.parse(Buffer.concat(chunks).toString('utf8')||'{}')}
function slugify(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,40)||'app'}
function validRequest(b){if(!/^[A-Za-z0-9_-]{3,72}$/.test(String(b.app_id||'')))return'invalid_app_id';if(!String(b.app_name||'').trim()||String(b.app_name).length>60)return'invalid_app_name';if(!/^https:\/\/zoryq-evm-node-live-production\.up\.railway\.app\/project-launch#app=/.test(String(b.app_url||'')))return'invalid_app_url';return null}
function xmlEscape(s){return String(s).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function javaString(s){return String(s).replace(/\\/g,'\\\\').replace(/"/g,'\\"')}
function run(cmd,args,opts={}){return new Promise((resolve,reject)=>{const p=spawn(cmd,args,{...opts,env:{...process.env,...(opts.env||{})}});let out='',err='';p.stdout?.on('data',d=>out+=d);p.stderr?.on('data',d=>err+=d);p.on('error',reject);p.on('close',code=>code===0?resolve({out,err}):reject(new Error(`${cmd} exited ${code}\n${out}\n${err}`)))})}
function buildTools(){const root=process.env.ANDROID_SDK_ROOT||process.env.ANDROID_HOME||'/opt/android-sdk-linux',base=path.join(root,'build-tools'),versions=fs.readdirSync(base).filter(v=>fs.statSync(path.join(base,v)).isDirectory()).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));if(!versions.length)throw Error('android_build_tools_missing');const dir=path.join(base,versions.at(-1));return{dir,apksigner:path.join(dir,'apksigner'),zipalign:path.join(dir,'zipalign'),aapt:fs.existsSync(path.join(dir,'aapt2'))?path.join(dir,'aapt2'):path.join(dir,'aapt')}}
function updateJob(id,patch){const j={...(jobs.get(id)||{}),...patch,updatedAt:new Date().toISOString()};jobs.set(id,j);fs.writeFileSync(path.join(JOB_ROOT,`${id}.json`),JSON.stringify(j,null,2));return j}
async function buildJob(id,input){active=true;const work=fs.mkdtempSync(path.join(os.tmpdir(),'zoryq-apk-'));try{updateJob(id,{status:'building'});fs.cpSync(TEMPLATE,work,{recursive:true});const hash=crypto.createHash('sha256').update(input.app_id).digest('hex').slice(0,12),packageId=`network.zoryq.generated.app${hash}`,versionCode=Math.min(2_100_000_000,Math.max(1,Math.floor(Date.now()/1000))),versionName=`1.0.${versionCode}`;const java=path.join(work,'app/src/main/java/network/zoryq/budgetforecast/MainActivity.java'),manifest=path.join(work,'app/src/main/AndroidManifest.xml'),gradle=path.join(work,'app/build.gradle');let src=fs.readFileSync(java,'utf8');src=src.replace(/private static final String FACTORY_URL = .*?;/,`private static final String FACTORY_URL = "${javaString(input.app_url)}";`).replace(' ZORYQ-App-Runner-Android/1.1',' ZORYQ-Standalone-App-Android/1.0');fs.writeFileSync(java,src);let xml=fs.readFileSync(manifest,'utf8').replace(/android:label="[^"]*"/,`android:label="${xmlEscape(input.app_name)}"`);fs.writeFileSync(manifest,xml);let g=fs.readFileSync(gradle,'utf8').replace(/applicationId\s+'[^']+'/,`applicationId '${packageId}'`).replace(/versionCode\s+\d+/,`versionCode ${versionCode}`).replace(/versionName\s+'[^']+'/,`versionName '${versionName}'`).replace(/debug\s*\{\s*debuggable\s+true\s*\}/m,'debug {\n            signingConfig null\n            debuggable false\n        }');fs.writeFileSync(gradle,g);
 if(!fs.existsSync(keystore)||!KEY_ALIAS||!KEYSTORE_PASSWORD||!KEY_PASSWORD)throw Error('release_signing_not_configured');
 await run('gradle',[':app:assembleDebug','--no-daemon','--max-workers=1'],{cwd:work});
 const candidates=[path.join(work,'app/build/outputs/apk/debug/app-debug-unsigned.apk'),path.join(work,'app/build/outputs/apk/debug/app-debug.apk')],unsigned=candidates.find(fs.existsSync);if(!unsigned)throw Error('factory_apk_missing');
 const tools=buildTools(),aligned=path.join(work,'aligned.apk'),finalApk=path.join(JOB_ROOT,`${id}.apk`);await run(tools.zipalign,['-f','-P','16','4',unsigned,aligned]);await run(tools.apksigner,['sign','--ks',keystore,'--ks-key-alias',KEY_ALIAS,'--ks-pass','env:KS_PASS','--key-pass','env:KEY_PASS','--out',finalApk,aligned],{env:{KS_PASS:KEYSTORE_PASSWORD,KEY_PASS:KEY_PASSWORD}});const verified=await run(tools.apksigner,['verify','--verbose','--print-certs',finalApk]);await run(tools.zipalign,['-c','-P','16','-v','4',finalApk]);const badging=await run(tools.aapt,['dump','badging',finalApk]);if(!badging.out.includes(`package: name='${packageId}'`))throw Error('package_identity_verification_failed');if(!verified.out.includes('Verified using v2 scheme (APK Signature Scheme v2): true'))throw Error('signature_v2_verification_failed');if(badging.out.includes('application-debuggable'))throw Error('debuggable_flag_must_be_off');const sha256=crypto.createHash('sha256').update(fs.readFileSync(finalApk)).digest('hex'),certMatch=verified.out.match(/(?:Signer #1|V2 Signer): certificate SHA-256 digest: ([0-9a-f]+)/i),cert=certMatch?certMatch[1]:null;if(!cert)throw Error('certificate_fingerprint_missing');updateJob(id,{status:'ready',appId:input.app_id,appName:input.app_name,packageId,versionCode,versionName,sha256,certificateSha256:cert,signing:'permanent-release-key',buildVariant:'lightweight-nondebuggable',downloadUrl:`/factory/apk/jobs/${id}/apk`});
 }catch(e){console.error('[factory-apk]',id,e);updateJob(id,{status:'failed',error:String(e.message||e).slice(0,1200)})}finally{fs.rmSync(work,{recursive:true,force:true});active=false}}

const server=http.createServer(async(req,res)=>{try{cors(req,res);if(req.method==='OPTIONS'){res.writeHead(204);return res.end()}const url=new URL(req.url,'http://127.0.0.1');if(req.method==='GET'&&url.pathname==='/health')return send(req,res,200,{ok:true,service:'zoryq-factory-apk-builder',signingConfigured:!!(fs.existsSync(keystore)&&KEY_ALIAS&&KEYSTORE_PASSWORD&&KEY_PASSWORD),active});if(req.method==='POST'&&url.pathname==='/factory/apk/build'){if(String(req.headers.origin||'')!==ORIGIN)return send(req,res,403,{ok:false,error:'origin_not_allowed'});const ip=clientIp(req);if(!allow(ip))return send(req,res,429,{ok:false,error:'build_rate_limit'});if(active)return send(req,res,503,{ok:false,error:'builder_busy',retryAfterSeconds:20});const body=await readJson(req),err=validRequest(body);if(err)return send(req,res,400,{ok:false,error:err});const id=crypto.randomUUID(),input={app_name:String(body.app_name).trim(),app_id:String(body.app_id),app_slug:slugify(body.app_slug||body.app_name),app_url:String(body.app_url)};updateJob(id,{id,status:'queued',createdAt:new Date().toISOString(),appId:input.app_id,appName:input.app_name});setImmediate(()=>buildJob(id,input));return send(req,res,202,{ok:true,id,status:'queued',statusUrl:`/factory/apk/jobs/${id}`})}const m=url.pathname.match(/^\/factory\/apk\/jobs\/([0-9a-f-]+)$/i);if(req.method==='GET'&&m){const j=jobs.get(m[1])||(()=>{try{return JSON.parse(fs.readFileSync(path.join(JOB_ROOT,`${m[1]}.json`),'utf8'))}catch{return null}})();return j?send(req,res,200,{ok:true,...j}):send(req,res,404,{ok:false,error:'job_not_found'})}const d=url.pathname.match(/^\/factory\/apk\/jobs\/([0-9a-f-]+)\/apk$/i);if(req.method==='GET'&&d){const file=path.join(JOB_ROOT,`${d[1]}.apk`);if(!fs.existsSync(file))return send(req,res,404,{ok:false,error:'apk_not_ready'});const meta=jobs.get(d[1])||{};cors(req,res);res.writeHead(200,{'content-type':'application/vnd.android.package-archive','content-disposition':`attachment; filename="ZORYQ-${slugify(meta.appName||'app')}.apk"`,'cache-control':'private, no-store'});return fs.createReadStream(file).pipe(res)}return send(req,res,404,{ok:false,error:'not_found'})}catch(e){return send(req,res,500,{ok:false,error:String(e.message||e).slice(0,500)})}});
server.listen(PORT,'0.0.0.0',()=>console.log(`[factory-apk] listening on :${PORT}`));
