import 'react-native-get-random-values';
import React,{useEffect,useMemo,useState} from 'react';
import {Alert,Linking,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import * as SecureStore from 'expo-secure-store';
import * as Clipboard from 'expo-clipboard';
import {Contract,HDNodeWallet,JsonRpcProvider,Wallet,formatEther,isAddress,parseEther} from 'ethers';
import {StatusBar} from 'expo-status-bar';

const BASE=process.env.EXPO_PUBLIC_ZORYQ_BASE||'https://zoryq-evm-node-v5-production.up.railway.app';
const RPC=process.env.EXPO_PUBLIC_ZORYQ_RPC||`${BASE}/rpc`;
const EXPLORER=process.env.EXPO_PUBLIC_ZORYQ_EXPLORER||'https://zoryq-testnet.vercel.app/explorer.html';
const REWARD_REGISTRY=process.env.EXPO_PUBLIC_REWARD_REGISTRY||'0x0000000000000000000000000000000000000000';
const QUEST_REGISTRY=process.env.EXPO_PUBLIC_QUEST_REGISTRY||'0x0000000000000000000000000000000000000000';
const STAKE_CONTRACT=process.env.EXPO_PUBLIC_STAKE_CONTRACT||'0x0000000000000000000000000000000000000000';
const CHAIN_ID=5919065;const KEY='zoryq.wallet.privateKey';const ZERO='0x0000000000000000000000000000000000000000';
const REWARD_ABI=['function scoreOf(address) view returns (uint256 total,uint256 mobile,uint256 contributor,uint256 validator,uint256 claimed,uint256 claimablePoints)'];
const QUEST_ABI=['function nextQuestId() view returns(uint256)','function quests(uint256) view returns(uint256 id,string title,string metadataURI,uint256 points,uint64 startAt,uint64 endAt,bool active)','function isQuestLive(uint256) view returns(bool)'];
const STAKE_ABI=['function staked(address) view returns(uint256)','function position(address) view returns(uint256 amount,uint64 since,uint256 ageSeconds)','function stake() payable','function unstake(uint256)'];

type AppWallet=Wallet|HDNodeWallet;
type Tab='home'|'send'|'stake'|'quests'|'rank'|'activity'|'settings';
type Quest={id:string;title:string;description:string;points:number;status:'active'|'upcoming'|'ended'|'paused';type:string};
type Score={total:number;mobile:number;contributor:number;validator:number;claimable:number};
const fallbackQuests:Quest[]=[
 {id:'first-tx',title:'Primeira transação',description:'Envie uma transação na ZORYQ Testnet.',points:100,status:'active',type:'onchain_tx'},
 {id:'faucet',title:'Pegue ZQ no Faucet',description:'Faça um claim de ZQ Testnet.',points:50,status:'active',type:'faucet_claim'},
 {id:'nft',title:'Mint seu primeiro NFT',description:'Interaja com um ERC-721 na ZORYQ.',points:500,status:'active',type:'nft_hold'}
];
function level(p:number){if(p>=100000)return'Genesis';if(p>=50000)return'Architect';if(p>=20000)return'Pioneer III';if(p>=10000)return'Pioneer II';if(p>=5000)return'Pioneer I';if(p>=1000)return'Explorer';return'Initiate'}
function questStatus(active:boolean,startAt:number,endAt:number):Quest['status']{const now=Math.floor(Date.now()/1000);if(!active)return'paused';if(startAt&&now<startAt)return'upcoming';if(endAt&&now>endAt)return'ended';return'active'}

export default function App(){
 const provider=useMemo(()=>new JsonRpcProvider(RPC,CHAIN_ID,{staticNetwork:true}),[]);
 const [wallet,setWallet]=useState<AppWallet|null>(null);const [balance,setBalance]=useState('0.0000');const [block,setBlock]=useState<number|null>(null);
 const [tab,setTab]=useState<Tab>('home');const [to,setTo]=useState('');const [amount,setAmount]=useState('');const [stakeAmount,setStakeAmount]=useState('');const [busy,setBusy]=useState(false);
 const [score,setScore]=useState<Score>({total:0,mobile:0,contributor:0,validator:0,claimable:0});const [quests,setQuests]=useState<Quest[]>(fallbackQuests);const [stakedZq,setStakedZq]=useState('0.0000');const [stakeAge,setStakeAge]=useState(0);
 useEffect(()=>{(async()=>{const pk=await SecureStore.getItemAsync(KEY);if(pk)setWallet(new Wallet(pk,provider))})()},[]);
 useEffect(()=>{if(!wallet)return;refresh();const i=setInterval(refresh,10000);return()=>clearInterval(i)},[wallet]);
 async function refresh(){if(!wallet)return;try{const [bal,bn]=await Promise.all([provider.getBalance(wallet.address),provider.getBlockNumber()]);setBalance(Number(formatEther(bal)).toFixed(4));setBlock(bn);if(REWARD_REGISTRY!==ZERO){const x=await new Contract(REWARD_REGISTRY,REWARD_ABI,provider).scoreOf(wallet.address);setScore({total:Number(x.total),mobile:Number(x.mobile),contributor:Number(x.contributor),validator:Number(x.validator),claimable:Number(x.claimablePoints)})}if(STAKE_CONTRACT!==ZERO){const p=await new Contract(STAKE_CONTRACT,STAKE_ABI,provider).position(wallet.address);setStakedZq(Number(formatEther(p.amount)).toFixed(4));setStakeAge(Number(p.ageSeconds))}if(QUEST_REGISTRY!==ZERO)await loadQuests()}catch{setBlock(null)}}
 async function loadQuests(){try{const c=new Contract(QUEST_REGISTRY,QUEST_ABI,provider);const next=Number(await c.nextQuestId());const ids=Array.from({length:Math.max(0,Math.min(next-1,50))},(_,i)=>i+1);const rows=await Promise.all(ids.map(async id=>{const q=await c.quests(id);return {id:String(id),title:String(q.title),description:String(q.metadataURI||'Quest registrada on-chain'),points:Number(q.points),status:questStatus(Boolean(q.active),Number(q.startAt),Number(q.endAt)),type:'quest_registry'} as Quest}));setQuests(rows.length?rows:fallbackQuests)}catch{setQuests(fallbackQuests)}}
 async function createWallet(){const w=Wallet.createRandom().connect(provider);await SecureStore.setItemAsync(KEY,w.privateKey);setWallet(w);Alert.alert('Wallet criada','A chave foi armazenada no SecureStore deste aparelho. Antes de usar valores reais no futuro, a ZORYQ terá um fluxo dedicado de backup/recovery. Nesta Testnet, ZQ não possui valor financeiro.');}
 async function importWallet(){Alert.alert('Importação segura','A importação de seed/private key permanece bloqueada nesta build até o fluxo de backup/recovery ser revisado. A ZORYQ nunca enviará chaves ao servidor.');}
 async function faucet(){if(!wallet)return;setBusy(true);try{const r=await fetch(`${BASE}/faucet`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({address:wallet.address})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Faucet indisponível');Alert.alert('Faucet',`Claim enviado: ${j.amount||100} ZQ Testnet`);await refresh()}catch(e:any){Alert.alert('Faucet',e.message)}finally{setBusy(false)}}
 async function send(){if(!wallet||!isAddress(to)||!amount)return Alert.alert('Dados inválidos','Confira endereço e valor.');setBusy(true);try{const tx=await wallet.sendTransaction({to,value:parseEther(amount)});Alert.alert('Transação enviada',tx.hash);setTo('');setAmount('');await tx.wait();await refresh();setTab('home')}catch(e:any){Alert.alert('Falha',e.shortMessage||e.message)}finally{setBusy(false)}}
 async function stake(){if(!wallet||STAKE_CONTRACT===ZERO)return Alert.alert('Stake ainda não ativado','O contrato de stake será habilitado quando for implantado na Testnet pública.');if(!stakeAmount||Number(stakeAmount)<=0)return Alert.alert('Valor inválido','Informe a quantidade de ZQ Testnet.');setBusy(true);try{const c=new Contract(STAKE_CONTRACT,STAKE_ABI,wallet);const tx=await c.stake({value:parseEther(stakeAmount)});Alert.alert('Stake enviado',tx.hash);await tx.wait();setStakeAmount('');await refresh()}catch(e:any){Alert.alert('Falha no stake',e.shortMessage||e.message)}finally{setBusy(false)}}
 async function unstakeAll(){if(!wallet||STAKE_CONTRACT===ZERO)return;if(Number(stakedZq)<=0)return Alert.alert('Sem stake','Não há ZQ em stake nesta wallet.');setBusy(true);try{const c=new Contract(STAKE_CONTRACT,STAKE_ABI,wallet);const raw=await c.staked(wallet.address);const tx=await c.unstake(raw);Alert.alert('Unstake enviado',tx.hash);await tx.wait();await refresh()}catch(e:any){Alert.alert('Falha no unstake',e.shortMessage||e.message)}finally{setBusy(false)}}
 if(!wallet)return <SafeAreaView style={s.root}><StatusBar style="light"/><View style={s.onboard}><Text style={s.brand}>ZORYQ</Text><Text style={s.h1}>Sua entrada para a ZORYQ Testnet.</Text><Text style={s.muted}>Wallet, ZQ, quests, stake, Score, nodes e atividade verificável na chain.</Text><Pressable style={s.primary} onPress={createWallet}><Text style={s.primaryText}>Criar nova wallet</Text></Pressable><Pressable style={s.secondary} onPress={importWallet}><Text style={s.secondaryText}>Importar wallet</Text></Pressable><Text style={s.note}>Chain ID {CHAIN_ID} • Self-custody • ZQ Testnet não possui valor financeiro.</Text></View></SafeAreaView>;
 return <SafeAreaView style={s.root}><StatusBar style="light"/><ScrollView contentContainerStyle={s.page}><View style={s.top}><Text style={s.brand}>ZORYQ</Text><Text style={s.net}>{block===null?'● RPC offline':'● Testnet online'}</Text></View>
 {tab==='home'&&<><Text style={s.label}>SALDO</Text><Text style={s.balance}>{balance} <Text style={s.zq}>ZQ</Text></Text><Pressable onPress={()=>Clipboard.setStringAsync(wallet.address)}><Text style={s.address}>{wallet.address}</Text></Pressable><View style={s.row}><Pressable style={s.primarySmall} onPress={()=>setTab('send')}><Text style={s.primaryText}>Enviar</Text></Pressable><Pressable style={s.secondarySmall} disabled={busy} onPress={faucet}><Text style={s.secondaryText}>Faucet</Text></Pressable><Pressable style={s.secondarySmall} onPress={()=>setTab('stake')}><Text style={s.secondaryText}>Stake</Text></Pressable></View><View style={s.cards}><Card title="ZORYQ Score" value={score.total.toLocaleString()} sub={`${level(score.total)} • finalizado on-chain`}/><Card title="ZQ em stake" value={`${stakedZq} ZQ`} sub={STAKE_CONTRACT===ZERO?'Contrato aguardando deploy':`${Math.floor(stakeAge/3600)}h na posição atual`}/><Card title="Validator" value={score.validator.toLocaleString()} sub="Maior peso de participação"/><Card title="Último bloco" value={block?.toString()||'—'} sub={`Chain ID ${CHAIN_ID}`}/></View></>}
 {tab==='send'&&<><Back onPress={()=>setTab('home')}/><Text style={s.h2}>Enviar ZQ</Text><TextInput style={s.input} placeholder="0x... destino" placeholderTextColor="#5d6473" value={to} onChangeText={setTo}/><TextInput style={s.input} placeholder="Quantidade ZQ" placeholderTextColor="#5d6473" keyboardType="decimal-pad" value={amount} onChangeText={setAmount}/><Pressable style={s.primary} disabled={busy} onPress={send}><Text style={s.primaryText}>{busy?'Enviando...':'Confirmar transação'}</Text></Pressable></>}
 {tab==='stake'&&<><Back onPress={()=>setTab('home')}/><Text style={s.h2}>Stake de ZQ Testnet</Text><Text style={s.muted}>O vault bloqueia e devolve ZQ Testnet. Ele não cria rendimento financeiro. Permanência e valor podem servir como evidência de participação para pontos Mobile.</Text><Card title="Posição atual" value={`${stakedZq} ZQ`} sub={STAKE_CONTRACT===ZERO?'Aguardando contrato público':`${Math.floor(stakeAge/3600)}h em stake`}/><TextInput style={s.input} placeholder="Quantidade ZQ" placeholderTextColor="#5d6473" keyboardType="decimal-pad" value={stakeAmount} onChangeText={setStakeAmount}/><Pressable style={s.primary} disabled={busy||STAKE_CONTRACT===ZERO} onPress={stake}><Text style={s.primaryText}>Colocar em stake</Text></Pressable><Pressable style={s.secondary} disabled={busy||STAKE_CONTRACT===ZERO} onPress={unstakeAll}><Text style={s.secondaryText}>Retirar todo stake</Text></Pressable></>}
 {tab==='quests'&&<><Text style={s.h2}>Quests & pontos</Text><Text style={s.muted}>{QUEST_REGISTRY===ZERO?'Mostrando quests de bootstrap até o Quest Registry ser implantado.':'Quests carregadas do ZORYQ Quest Registry.'} Pontos elegíveis são validados antes da finalização.</Text>{quests.map(q=><View key={q.id} style={s.quest}><View style={{flex:1}}><Text style={s.questTitle}>{q.title}</Text><Text style={s.muted}>{q.description}</Text><Text style={s.questType}>{q.type} • {q.status}</Text></View><Text style={s.points}>+{q.points}</Text></View>)}</>}
 {tab==='rank'&&<><Text style={s.h2}>Meu Score</Text><Card title="Nível" value={level(score.total)} sub={`${score.total.toLocaleString()} XP finalizado`}/><Card title="Validator" value={score.validator.toLocaleString()} sub="Node / infraestrutura validada"/><Card title="Builder" value={score.contributor.toLocaleString()} sub="Deploys e contribuições qualificadas"/><Card title="Mobile" value={score.mobile.toLocaleString()} sub="Quests, stake, swap e uso elegível"/><Pressable style={s.primary} onPress={()=>Linking.openURL('https://zoryq-testnet.vercel.app/leaderboard.html')}><Text style={s.primaryText}>Abrir ranking global</Text></Pressable></>}
 {tab==='activity'&&<><Text style={s.h2}>Chain</Text><Text style={s.muted}>Saldo, transações, tokens, NFTs, stake e rewards oficiais são consultados na ZORYQ Chain. O aplicativo não mantém um ledger financeiro paralelo.</Text><Pressable style={s.secondary} onPress={()=>Linking.openURL(`${EXPLORER}?q=${wallet.address}`)}><Text style={s.secondaryText}>Abrir minha wallet no Explorer</Text></Pressable></>}
 {tab==='settings'&&<><Text style={s.h2}>Rede</Text><Card title="Network" value="ZORYQ EVM Testnet" sub="EVM compatible"/><Card title="Chain ID" value="5919065" sub="0x5a5159"/><Card title="Reward Registry" value={REWARD_REGISTRY===ZERO?'Pending deploy':REWARD_REGISTRY} sub="Fonte do Score finalizado"/><Card title="Quest Registry" value={QUEST_REGISTRY===ZERO?'Pending deploy':QUEST_REGISTRY} sub="Fonte dinâmica das quests"/><Card title="Stake Vault" value={STAKE_CONTRACT===ZERO?'Pending deploy':STAKE_CONTRACT} sub="Stake nativo de ZQ Testnet"/><Text style={s.warning}>Nunca compartilhe sua seed ou private key. A ZORYQ não solicita essas informações.</Text></>}
 {tab!=='send'&&tab!=='stake'&&<View style={s.nav}>{(['home','quests','rank','activity','settings'] as Tab[]).map(x=><Pressable key={x} onPress={()=>setTab(x)} style={[s.navItem,tab===x&&s.navActive]}><Text style={s.navText}>{x==='home'?'Home':x==='quests'?'Quests':x==='rank'?'Rank':x==='activity'?'Chain':'Rede'}</Text></Pressable>)}</View>}</ScrollView></SafeAreaView>
}
function Card({title,value,sub}:{title:string;value:string;sub:string}){return <View style={s.card}><Text style={s.label}>{title}</Text><Text style={s.cardValue} numberOfLines={1}>{value}</Text><Text style={s.muted} numberOfLines={2}>{sub}</Text></View>}
function Back({onPress}:{onPress:()=>void}){return <Pressable onPress={onPress}><Text style={s.back}>← Voltar</Text></Pressable>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#050609'},page:{padding:20,paddingBottom:110},onboard:{flex:1,justifyContent:'center',padding:28},brand:{fontSize:22,fontWeight:'900',letterSpacing:5,color:'#fff'},h1:{fontSize:42,lineHeight:46,fontWeight:'900',color:'#fff',marginTop:28,marginBottom:14},h2:{fontSize:30,fontWeight:'900',color:'#fff',marginVertical:18},muted:{color:'#8b93a7',lineHeight:20},note:{color:'#697184',marginTop:18,fontSize:12},top:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginBottom:36},net:{color:'#b8ff49',fontWeight:'700'},label:{color:'#737b90',fontSize:11,fontWeight:'800',letterSpacing:1.2},balance:{fontSize:45,fontWeight:'900',color:'#fff',marginVertical:8},zq:{color:'#b8ff49'},address:{color:'#00e5ff',fontSize:12,marginBottom:22},back:{color:'#00e5ff',fontWeight:'800',marginTop:2},row:{flexDirection:'row',gap:8},primary:{backgroundColor:'#b8ff49',padding:16,borderRadius:15,alignItems:'center',marginTop:20},primarySmall:{flex:1,backgroundColor:'#b8ff49',padding:15,borderRadius:14,alignItems:'center'},primaryText:{color:'#071000',fontWeight:'900'},secondary:{borderWidth:1,borderColor:'#2a3040',padding:16,borderRadius:15,alignItems:'center',marginTop:10},secondarySmall:{flex:1,borderWidth:1,borderColor:'#2a3040',padding:15,borderRadius:14,alignItems:'center'},secondaryText:{color:'#fff',fontWeight:'800'},cards:{gap:10,marginTop:22},card:{backgroundColor:'#0c0f15',borderWidth:1,borderColor:'#202633',padding:17,borderRadius:18,marginTop:10},cardValue:{color:'#fff',fontSize:21,fontWeight:'800',marginVertical:7},input:{backgroundColor:'#0c0f15',borderWidth:1,borderColor:'#242a38',color:'#fff',padding:16,borderRadius:14,marginBottom:10},quest:{flexDirection:'row',gap:14,backgroundColor:'#0c0f15',borderWidth:1,borderColor:'#202633',padding:17,borderRadius:18,marginTop:10},questTitle:{color:'#fff',fontWeight:'800',fontSize:17},questType:{color:'#00e5ff',fontSize:11,marginTop:7},points:{color:'#b8ff49',fontWeight:'900',fontSize:20},warning:{color:'#ffcf66',marginTop:20,lineHeight:20},nav:{position:'absolute',left:10,right:10,bottom:18,backgroundColor:'#0a0d12',borderWidth:1,borderColor:'#222938',borderRadius:20,padding:6,flexDirection:'row'},navItem:{flex:1,paddingVertical:10,alignItems:'center',borderRadius:13},navActive:{backgroundColor:'#171d27'},navText:{color:'#dbe2ef',fontSize:10,fontWeight:'800'}});
