import React,{useEffect,useState} from 'react';
import {Alert,Pressable,RefreshControl,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';

const ROOT=String(process.env.EXPO_PUBLIC_ZORYQ_SWAP_BACKEND||'https://zoryq-wallet-swap-production.up.railway.app').replace(/\/$/,'');
const BASE=`${ROOT}/community`;
const SESSION_KEY='zoryq.social.session.v1';

type Community={id:string;slug:string;name:string;description:string;owner:string;visibility:string;members:number;channels:number;joined:boolean;viewerRole:string|null};
type Channel={id:string;communityId:string;slug:string;name:string;description:string;messageCount:number};
type Message={id:string;communityId:string;channelId:string;author:string;content:string;createdAt:number};
function short(a:string){return a?`${a.slice(0,6)}…${a.slice(-4)}`:'—'}
function err(e:any){return e?.message||'Falha inesperada'}
async function call(path:string,init:RequestInit={},token=''){const headers:any={'accept':'application/json',...(init.body?{'content-type':'application/json'}:{}),...(token?{authorization:`Bearer ${token}`}:{})};const r=await fetch(`${BASE}${path}`,{...init,headers:{...headers,...(init.headers||{})}});const j=await r.json().catch(()=>({ok:false,error:'INVALID_RESPONSE'}));if(!r.ok||j.ok===false)throw Error(j.error||`HTTP_${r.status}`);return j}

export default function CommunitiesApp({onBack}:{onBack:()=>void}){
 const [token,setToken]=useState('');const [items,setItems]=useState<Community[]>([]);const [selected,setSelected]=useState<Community|null>(null);const [channels,setChannels]=useState<Channel[]>([]);const [channel,setChannel]=useState<Channel|null>(null);const [messages,setMessages]=useState<Message[]>([]);const [draft,setDraft]=useState('');const [refreshing,setRefreshing]=useState(false);const [create,setCreate]=useState(false);const [name,setName]=useState('');const [slug,setSlug]=useState('');const [description,setDescription]=useState('');const [newChannel,setNewChannel]=useState('');
 useEffect(()=>{void boot()},[]);
 useEffect(()=>{if(!channel)return;const id=setInterval(()=>void loadMessages(channel),5000);return()=>clearInterval(id)},[channel?.id]);
 async function boot(){const t=await AsyncStorage.getItem(SESSION_KEY)||'';setToken(t);await load(t)}
 async function load(t=token){try{setRefreshing(true);const j=await call('/v1/communities',{},t);setItems(j.items||[])}catch(e){Alert.alert('Comunidades',err(e))}finally{setRefreshing(false)}}
 async function open(c:Community){try{const j=await call(`/v1/communities/${c.id}`,{},token);setSelected(j.community);setChannels(j.channels||[]);setChannel(null)}catch(e){Alert.alert('Comunidade',err(e))}}
 async function toggleJoin(){if(!selected)return;if(!token)return Alert.alert('Entre no Social','Autentique sua wallet no Social antes de entrar em comunidades.');try{const j=await call(`/v1/communities/${selected.id}/join`,{method:'POST'},token);setSelected(j.community);await load()}catch(e){Alert.alert('Comunidade',err(e))}}
 async function makeCommunity(){if(!token)return Alert.alert('Entre no Social','Autentique sua wallet antes de criar uma comunidade.');try{const j=await call('/v1/communities',{method:'POST',body:JSON.stringify({name,slug,description})},token);setName('');setSlug('');setDescription('');setCreate(false);await load();await open(j.community)}catch(e){Alert.alert('Criar comunidade',err(e))}}
 async function createChannel(){if(!selected||!newChannel.trim())return;try{const j=await call(`/v1/communities/${selected.id}/channels`,{method:'POST',body:JSON.stringify({name:newChannel,slug:newChannel,description:'Canal da comunidade'})},token);setNewChannel('');setChannels(x=>[...x,j.channel])}catch(e){Alert.alert('Canal',err(e))}}
 async function openChannel(c:Channel){setChannel(c);await loadMessages(c)}
 async function loadMessages(c=channel){if(!c)return;try{const j=await call(`/v1/channels/${c.id}/messages`,{},token);setMessages(j.items||[])}catch{}}
 async function send(){if(!channel||!draft.trim())return;if(!token)return Alert.alert('Entre no Social','Autentique sua wallet para conversar.');try{const j=await call(`/v1/channels/${channel.id}/messages`,{method:'POST',body:JSON.stringify({content:draft.trim()})},token);setMessages(x=>[...x,j.message]);setDraft('')}catch(e){Alert.alert('Mensagem',err(e))}}
 if(channel)return <SafeAreaView style={s.root}><Header title={`# ${channel.name}`} onBack={()=>setChannel(null)}/><ScrollView contentContainerStyle={s.chat}>{messages.length===0?<Text style={s.muted}>Comece a conversa neste canal.</Text>:messages.map(m=><View key={m.id} style={s.msg}><Text style={s.msgAuthor}>{short(m.author)}</Text><Text style={s.msgText}>{m.content}</Text><Text style={s.time}>{new Date(m.createdAt).toLocaleTimeString()}</Text></View>)}</ScrollView><View style={s.compose}><TextInput style={s.composeInput} value={draft} onChangeText={setDraft} maxLength={2000} placeholder="Mensagem…" placeholderTextColor="#687188"/><Pressable style={s.send} onPress={()=>void send()}><Text style={s.sendText}>Enviar</Text></Pressable></View></SafeAreaView>;
 if(selected)return <SafeAreaView style={s.root}><Header title={selected.name} onBack={()=>{setSelected(null);void load()}}/><ScrollView contentContainerStyle={s.scroll}><View style={s.hero}><Text style={s.title}>{selected.name}</Text><Text style={s.muted}>{selected.description||'Comunidade Web3 na ZORYQ.'}</Text><View style={s.row}><Text style={s.stat}>{selected.members} membros</Text><Text style={s.stat}>{selected.channels} canais</Text><Text style={s.stat}>{selected.viewerRole||'visitante'}</Text></View><Pressable style={[s.primary,selected.joined&&s.secondary]} onPress={()=>void toggleJoin()}><Text style={s.primaryText}>{selected.viewerRole==='owner'?'Você é o owner':selected.joined?'Sair da comunidade':'Entrar na comunidade'}</Text></Pressable></View><Text style={s.section}>Canais</Text>{channels.map(c=><Pressable key={c.id} style={s.card} onPress={()=>void openChannel(c)}><Text style={s.cardTitle}># {c.name}</Text><Text style={s.muted}>{c.description} · {c.messageCount} mensagens</Text></Pressable>)}{selected.viewerRole==='owner'?<View style={s.createBox}><Text style={s.label}>Novo canal</Text><TextInput style={s.input} value={newChannel} onChangeText={setNewChannel} placeholder="ex.: builders" placeholderTextColor="#687188"/><Pressable style={s.primary} onPress={()=>void createChannel()}><Text style={s.primaryText}>Criar canal</Text></Pressable></View>:null}</ScrollView></SafeAreaView>;
 return <SafeAreaView style={s.root}><Header title="Comunidades" onBack={onBack}/><ScrollView refreshControl={<RefreshControl refreshing={refreshing} onRefresh={()=>void load()} tintColor="#9c84ff"/>} contentContainerStyle={s.scroll}><View style={s.topRow}><View><Text style={s.title}>Encontre sua comunidade.</Text><Text style={s.muted}>Canais públicos ligados à identidade da wallet.</Text></View><Pressable style={s.plus} onPress={()=>setCreate(x=>!x)}><Text style={s.plusText}>＋</Text></Pressable></View>{create?<View style={s.createBox}><TextInput style={s.input} value={name} onChangeText={setName} placeholder="Nome" placeholderTextColor="#687188"/><TextInput style={s.input} value={slug} onChangeText={setSlug} autoCapitalize="none" placeholder="slug-da-comunidade" placeholderTextColor="#687188"/><TextInput style={[s.input,{minHeight:70}]} multiline value={description} onChangeText={setDescription} placeholder="Descrição" placeholderTextColor="#687188"/><Pressable style={s.primary} onPress={()=>void makeCommunity()}><Text style={s.primaryText}>Criar comunidade</Text></Pressable></View>:null}{items.length===0?<View style={s.empty}><Text style={s.cardTitle}>Nenhuma comunidade ainda.</Text><Text style={s.muted}>Crie a primeira comunidade ZORYQ.</Text></View>:items.map(c=><Pressable key={c.id} style={s.card} onPress={()=>void open(c)}><View style={s.rowBetween}><View style={s.grow}><Text style={s.cardTitle}>{c.name}</Text><Text style={s.slug}>/{c.slug}</Text></View>{c.joined?<Text style={s.joined}>ENTROU</Text>:null}</View><Text style={s.muted}>{c.description}</Text><View style={s.row}><Text style={s.stat}>{c.members} membros</Text><Text style={s.stat}>{c.channels} canais</Text></View></Pressable>)}</ScrollView></SafeAreaView>
}
function Header({title,onBack}:{title:string;onBack:()=>void}){return <View style={s.header}><Pressable onPress={onBack}><Text style={s.back}>←</Text></Pressable><Text style={s.headerTitle}>{title}</Text><View style={{width:26}}/></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#050609'},header:{height:52,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:13,borderBottomWidth:1,borderColor:'#171d29'},back:{color:'#9c84ff',fontSize:24,fontWeight:'900'},headerTitle:{color:'#fff',fontSize:16,fontWeight:'900'},scroll:{padding:13,paddingBottom:40,gap:11},title:{color:'#fff',fontSize:26,fontWeight:'900'},muted:{color:'#8791a5',lineHeight:19},topRow:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},plus:{width:42,height:42,borderRadius:21,backgroundColor:'#6248e8',alignItems:'center',justifyContent:'center'},plusText:{color:'#fff',fontSize:24,fontWeight:'700'},createBox:{backgroundColor:'#0c1018',borderRadius:16,padding:12,gap:9,borderWidth:1,borderColor:'#1b2433'},input:{color:'#fff',backgroundColor:'#111722',borderRadius:11,padding:11},primary:{backgroundColor:'#6248e8',borderRadius:11,padding:11,alignItems:'center'},secondary:{backgroundColor:'#22293a'},primaryText:{color:'#fff',fontWeight:'900'},card:{backgroundColor:'#0b1018',borderWidth:1,borderColor:'#182131',borderRadius:15,padding:13,gap:6},cardTitle:{color:'#fff',fontWeight:'900',fontSize:16},slug:{color:'#69738a',fontSize:11},row:{flexDirection:'row',gap:12,alignItems:'center'},rowBetween:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},grow:{flex:1},stat:{color:'#69758c',fontSize:11,fontWeight:'700'},joined:{color:'#5edbff',fontSize:9,fontWeight:'900'},section:{color:'#fff',fontSize:18,fontWeight:'900',marginTop:5},label:{color:'#a6afc1',fontWeight:'800',fontSize:11},hero:{gap:10},empty:{padding:25,alignItems:'center',gap:5},chat:{padding:12,paddingBottom:20,gap:8},msg:{backgroundColor:'#0d131c',borderRadius:12,padding:10,alignSelf:'stretch'},msgAuthor:{color:'#9c84ff',fontSize:10,fontWeight:'900'},msgText:{color:'#e1e5ed',fontSize:15,marginTop:3},time:{color:'#5d687c',fontSize:9,marginTop:4,alignSelf:'flex-end'},compose:{flexDirection:'row',gap:8,padding:10,borderTopWidth:1,borderColor:'#171d29'},composeInput:{flex:1,color:'#fff',backgroundColor:'#111722',borderRadius:12,paddingHorizontal:11,paddingVertical:10},send:{backgroundColor:'#6248e8',borderRadius:12,paddingHorizontal:14,justifyContent:'center'},sendText:{color:'#fff',fontWeight:'900'}});
