import React,{useEffect,useState} from 'react';
import {Alert,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';

const ROOT=String(process.env.EXPO_PUBLIC_ZORYQ_SWAP_BACKEND||'https://zoryq-wallet-swap-production.up.railway.app').replace(/\/$/,'');
const BASE=`${ROOT}/message`;const SOCIAL=`${ROOT}/social`;const SESSION_KEY='zoryq.social.session.v1';
type Profile={address:string;handle:string;displayName:string;bio:string};
type Conversation={id:string;participants:string[];createdAt:number;updatedAt:number;lastMessage?:{id:string;sender:string;content:string;createdAt:number}|null;unread:number};
type Message={id:string;conversationId:string;sender:string;content:string;createdAt:number;readBy:string[]};
function short(a:string){return a?`${a.slice(0,6)}…${a.slice(-4)}`:'—'}
function err(e:any){return e?.message||'Falha inesperada'}
async function api(base:string,path:string,init:RequestInit={},token=''){const headers:any={'accept':'application/json',...(init.body?{'content-type':'application/json'}:{}),...(token?{authorization:`Bearer ${token}`}:{})};const r=await fetch(`${base}${path}`,{...init,headers:{...headers,...(init.headers||{})}});const j=await r.json().catch(()=>({ok:false,error:'INVALID_RESPONSE'}));if(!r.ok||j.ok===false)throw Error(j.error||`HTTP_${r.status}`);return j}

export default function MessagesApp({onBack}:{onBack:()=>void}){
 const [token,setToken]=useState('');const [walletAddress,setWalletAddress]=useState('');const [items,setItems]=useState<Conversation[]>([]);const [profiles,setProfiles]=useState<Record<string,Profile>>({});const [open,setOpen]=useState<Conversation|null>(null);const [messages,setMessages]=useState<Message[]>([]);const [draft,setDraft]=useState('');const [search,setSearch]=useState('');const [results,setResults]=useState<Profile[]>([]);const [busy,setBusy]=useState(false);
 useEffect(()=>{void boot()},[]);useEffect(()=>{if(!open)return;const id=setInterval(()=>void loadThread(open),4000);return()=>clearInterval(id)},[open?.id]);
 async function boot(){const t=await AsyncStorage.getItem(SESSION_KEY)||'';setToken(t);if(!t)return;try{const list=await api(BASE,'/v1/conversations',{},t);setItems(list.items||[]);const first=(list.items||[])[0];if(first){const mine=await inferSelf(first,t);setWalletAddress(mine)}await hydrateProfiles(list.items||[],t)}catch(e){Alert.alert('Mensagens',err(e))}}
 async function inferSelf(c:Conversation,t:string){for(const p of c.participants){try{const prof=await api(SOCIAL,`/v1/profile/${p}`,{},t);if(prof.profile){setProfiles(x=>({...x,[p.toLowerCase()]:prof.profile}))}}catch{}}return ''}
 async function hydrateProfiles(cs:Conversation[],t=token){const addresses=[...new Set(cs.flatMap(c=>c.participants))];for(const a of addresses){if(profiles[a.toLowerCase()])continue;try{const p=await api(SOCIAL,`/v1/profile/${a}`,{},t);setProfiles(x=>({...x,[a.toLowerCase()]:p.profile}))}catch{}}}
 async function refresh(){if(!token)return;try{const j=await api(BASE,'/v1/conversations',{},token);setItems(j.items||[]);await hydrateProfiles(j.items||[])}catch(e){Alert.alert('Mensagens',err(e))}}
 async function runSearch(){const q=search.trim();if(q.length<2)return;setBusy(true);try{if(/^0x[a-fA-F0-9]{40}$/.test(q)){const p=await api(SOCIAL,`/v1/profile/${q}`,{},token);setResults([p.profile])}else{const j=await api(SOCIAL,`/v1/search?q=${encodeURIComponent(q.replace(/^@/,''))}`,{},token);setResults(j.users||[])}}catch(e){Alert.alert('Buscar pessoa',err(e))}finally{setBusy(false)}}
 async function begin(p:Profile){if(!token)return Alert.alert('Entre no Social','Autentique sua wallet para iniciar conversas.');try{const j=await api(BASE,'/v1/conversations',{method:'POST',body:JSON.stringify({participant:p.address})},token);setResults([]);setSearch('');setProfiles(x=>({...x,[p.address.toLowerCase()]:p}));await openConversation(j.conversation);await refresh()}catch(e){Alert.alert('Nova conversa',err(e))}}
 async function openConversation(c:Conversation){setOpen(c);await loadThread(c);try{await api(BASE,`/v1/conversations/${c.id}/read`,{method:'POST'},token)}catch{} }
 async function loadThread(c=open){if(!c)return;try{const j=await api(BASE,`/v1/conversations/${c.id}/messages`,{},token);setMessages(j.items||[]);if(j.conversation?.participants)await hydrateProfiles([j.conversation])}catch{}}
 async function send(){if(!open||!draft.trim())return;try{const j=await api(BASE,`/v1/conversations/${open.id}/messages`,{method:'POST',body:JSON.stringify({content:draft.trim()})},token);setMessages(x=>[...x,j.message]);setDraft('');await refresh()}catch(e){Alert.alert('Mensagem',err(e))}}
 function other(c:Conversation){const known=c.participants.find(a=>a.toLowerCase()!==walletAddress.toLowerCase());return known||c.participants[0]||''}
 function display(a:string){const p=profiles[a.toLowerCase()];return p?`${p.displayName} · @${p.handle}`:short(a)}
 if(!token)return <SafeAreaView style={s.root}><Header title="Mensagens" onBack={onBack}/><View style={s.center}><Text style={s.title}>Entre com sua Wallet</Text><Text style={s.muted}>Faça login no Social primeiro para usar mensagens diretas.</Text></View></SafeAreaView>;
 if(open){const counterpart=other(open);return <SafeAreaView style={s.root}><Header title={display(counterpart)} onBack={()=>{setOpen(null);void refresh()}}/><View style={s.warning}><Text style={s.warningText}>Privada por controle de acesso. Ainda não possui criptografia ponta a ponta.</Text></View><ScrollView contentContainerStyle={s.chat}>{messages.map(m=><View key={m.id} style={[s.bubble,m.sender.toLowerCase()===counterpart.toLowerCase()?s.their:s.mine]}><Text style={s.msgText}>{m.content}</Text><Text style={s.time}>{new Date(m.createdAt).toLocaleTimeString()}</Text></View>)}</ScrollView><View style={s.compose}><TextInput style={s.input} value={draft} onChangeText={setDraft} maxLength={4000} placeholder="Mensagem…" placeholderTextColor="#687188"/><Pressable style={s.send} onPress={()=>void send()}><Text style={s.sendText}>Enviar</Text></Pressable></View></SafeAreaView>}
 return <SafeAreaView style={s.root}><Header title="Mensagens" onBack={onBack}/><ScrollView contentContainerStyle={s.scroll}><View style={s.searchRow}><TextInput style={s.searchInput} value={search} onChangeText={setSearch} onSubmitEditing={()=>void runSearch()} placeholder="Buscar @usuário ou wallet" placeholderTextColor="#687188"/><Pressable style={s.searchBtn} onPress={()=>void runSearch()}><Text style={s.sendText}>{busy?'…':'Buscar'}</Text></Pressable></View>{results.map(p=><Pressable key={p.address} style={s.person} onPress={()=>void begin(p)}><Avatar p={p}/><View style={s.grow}><Text style={s.personName}>{p.displayName}</Text><Text style={s.handle}>@{p.handle} · {short(p.address)}</Text><Text style={s.bio} numberOfLines={1}>{p.bio}</Text></View><Text style={s.link}>Mensagem</Text></Pressable>)}<View style={s.heading}><Text style={s.title}>Conversas</Text><Pressable onPress={()=>void refresh()}><Text style={s.link}>Atualizar</Text></Pressable></View>{items.length===0?<View style={s.empty}><Text style={s.personName}>Nenhuma conversa ainda.</Text><Text style={s.muted}>Busque um perfil e inicie uma conversa wallet-to-wallet.</Text></View>:items.map(c=>{const a=other(c);return <Pressable key={c.id} style={s.convo} onPress={()=>void openConversation(c)}><Avatar p={profiles[a.toLowerCase()]}/><View style={s.grow}><Text style={s.personName}>{display(a)}</Text><Text style={s.preview} numberOfLines={1}>{c.lastMessage?.content||'Conversa iniciada'}</Text></View>{c.unread>0?<View style={s.badge}><Text style={s.badgeText}>{c.unread>9?'9+':c.unread}</Text></View>:null}</Pressable>})}<View style={s.notice}><Text style={s.noticeTitle}>Privacidade atual</Text><Text style={s.muted}>As conversas exigem autenticação por wallet e somente os participantes podem acessá-las. O servidor ainda processa o conteúdo; E2E será uma etapa separada.</Text></View></ScrollView></SafeAreaView>
}
function Header({title,onBack}:{title:string;onBack:()=>void}){return <View style={s.header}><Pressable onPress={onBack}><Text style={s.back}>←</Text></Pressable><Text style={s.headerTitle}>{title}</Text><View style={{width:26}}/></View>}
function Avatar({p}:{p?:Profile}){return <View style={s.avatar}><Text style={s.avatarText}>{(p?.displayName||'Z').slice(0,1).toUpperCase()}</Text></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:'#050609'},header:{height:52,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:13,borderBottomWidth:1,borderColor:'#171d29'},back:{color:'#9c84ff',fontSize:24,fontWeight:'900'},headerTitle:{color:'#fff',fontWeight:'900',fontSize:16},scroll:{padding:12,paddingBottom:40,gap:10},searchRow:{flexDirection:'row',gap:8},searchInput:{flex:1,color:'#fff',backgroundColor:'#111722',borderRadius:12,paddingHorizontal:12,paddingVertical:10},searchBtn:{backgroundColor:'#6248e8',borderRadius:12,paddingHorizontal:13,justifyContent:'center'},sendText:{color:'#fff',fontWeight:'900'},person:{flexDirection:'row',alignItems:'center',gap:10,backgroundColor:'#0c1018',borderRadius:14,padding:10},avatar:{width:44,height:44,borderRadius:22,backgroundColor:'#6248e8',alignItems:'center',justifyContent:'center'},avatarText:{color:'#fff',fontWeight:'900',fontSize:18},grow:{flex:1},personName:{color:'#fff',fontWeight:'900'},handle:{color:'#788298',fontSize:11},bio:{color:'#657086',fontSize:10,marginTop:2},link:{color:'#9c84ff',fontWeight:'900',fontSize:11},heading:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:7},title:{color:'#fff',fontSize:22,fontWeight:'900'},muted:{color:'#8791a5',lineHeight:19,textAlign:'center'},convo:{flexDirection:'row',gap:10,alignItems:'center',backgroundColor:'#0b1018',borderRadius:14,padding:11},preview:{color:'#7d879b',fontSize:11,marginTop:3},badge:{minWidth:23,height:23,borderRadius:12,backgroundColor:'#ff4f7b',alignItems:'center',justifyContent:'center'},badgeText:{color:'#fff',fontWeight:'900',fontSize:10},empty:{padding:28,alignItems:'center',gap:5},notice:{backgroundColor:'#0d121b',borderRadius:14,padding:12,gap:5,borderWidth:1,borderColor:'#20293a'},noticeTitle:{color:'#f0c46a',fontWeight:'900'},center:{flex:1,alignItems:'center',justifyContent:'center',padding:30,gap:8},warning:{padding:8,backgroundColor:'#241f12'},warningText:{color:'#e8c46d',textAlign:'center',fontSize:10,fontWeight:'700'},chat:{padding:12,paddingBottom:20,gap:8},bubble:{maxWidth:'84%',borderRadius:14,padding:10},their:{alignSelf:'flex-start',backgroundColor:'#101722'},mine:{alignSelf:'flex-end',backgroundColor:'#392c7a'},msgText:{color:'#fff',fontSize:15,lineHeight:20},time:{color:'#8690a3',fontSize:8,alignSelf:'flex-end',marginTop:4},compose:{flexDirection:'row',gap:8,padding:10,borderTopWidth:1,borderColor:'#171d29'},input:{flex:1,color:'#fff',backgroundColor:'#111722',borderRadius:12,paddingHorizontal:11,paddingVertical:10},send:{backgroundColor:'#6248e8',borderRadius:12,paddingHorizontal:14,justifyContent:'center'}});
