import React,{useEffect,useMemo,useState} from 'react';
import {Pressable,SafeAreaView,ScrollView,StyleSheet,Text,View} from 'react-native';
import {ZORYQ_UI} from './theme';
import ZoryqMobileNode,{MobileNodeStatus,NodeMode} from './modules/zoryq-mobile-node/src/ZoryqMobileNodeModule';
import {MobileNodeApiClient,type XpResult} from './modules/zoryq-mobile-node/src/MobileNodeApiClient';

type Props={onBack:()=>void};
const EMPTY:MobileNodeStatus={running:false,state:'Offline',nodeKeyHardwareBacked:false,lastBlock:-1,rpcHealthyCount:0,rpcAgreementVotes:0,independentRpcAgreement:false,mode:'BALANCED',minBatteryPct:20,chargingOnly:false,wifiOnly:false,mobileDataAllowed:true,lastLocalProofXp:0};
const MOBILE_NODE_API_URL=process.env.EXPO_PUBLIC_ZORYQ_MOBILE_NODE_API_URL?.trim()||'';

export default function MobileNodeApp({onBack}:Props){
 const [node,setNode]=useState<MobileNodeStatus>(EMPTY);
 const [warning,setWarning]=useState('');
 const [busy,setBusy]=useState(false);
 const [serverXp,setServerXp]=useState<number|null>(null);
 const [serverState,setServerState]=useState(MOBILE_NODE_API_URL?'não registrado':'API não configurada');
 const [lastReward,setLastReward]=useState<XpResult|null>(null);
 const api=useMemo(()=>MOBILE_NODE_API_URL?new MobileNodeApiClient(MOBILE_NODE_API_URL):null,[]);
 useEffect(()=>{void refresh();const timer=setInterval(()=>void refresh(),2000);return()=>clearInterval(timer)},[]);
 async function refresh(){try{setNode(await ZoryqMobileNode.getStatus())}catch(e:any){setWarning(e?.message||'Native Mobile Node unavailable')}}
 async function action(fn:()=>Promise<MobileNodeStatus>){if(busy)return;setBusy(true);setWarning('');try{setNode(await fn())}catch(e:any){setWarning(e?.message||'Mobile Node action failed')}finally{setBusy(false)}}
 async function setMode(mode:NodeMode){await action(()=>ZoryqMobileNode.setPolicy(mode,node.minBatteryPct,node.chargingOnly,node.wifiOnly,node.mobileDataAllowed))}
 async function serverAction(fn:()=>Promise<void>){if(busy)return;setBusy(true);setWarning('');try{await fn()}catch(e:any){setWarning(e?.message||'Mobile Node server action failed')}finally{setBusy(false)}}
 async function registerNode(){if(!api)throw new Error('Configure EXPO_PUBLIC_ZORYQ_MOBILE_NODE_API_URL antes de registrar o node');const result=await api.register();setServerState(`registrado ${result.registeredAt}`);setServerXp(await api.getXp(result.nodeId))}
 async function refreshXp(){if(!api)throw new Error('Mobile Node API não configurada');const xp=await api.getXp();setServerXp(xp);setServerState('XP consultado no servidor')}
 async function submitProof(){if(!api)throw new Error('Mobile Node API não configurada');const current=await ZoryqMobileNode.getStatus();const result=await api.submitCurrentWitness(current);setLastReward(result);setServerXp(result.xpBalance);setServerState(`proof verificada ${result.verifiedAt}`)}
 return <SafeAreaView style={s.root}><ScrollView contentContainerStyle={s.content}>
  <View style={s.header}><Pressable onPress={onBack}><Text style={s.back}>← ZORYQ</Text></Pressable><View><Text style={s.kicker}>NETWORK PARTICIPATION</Text><Text style={s.title}>Mobile Node</Text></View></View>
  <View style={[s.hero,node.running&&s.heroOn]}><Text style={s.state}>{node.running?'● NATIVE WITNESS ACTIVE':'○ OFFLINE'}</Text><Text style={s.heroTitle}>Verificação nativa em segundo plano.</Text><Text style={s.copy}>O Mobile Node usa um Foreground Service visível do Android. A identidade do node é separada da carteira e a observação local nunca concede XP sozinha. Este observer não é um validator.</Text><View style={s.actions}><Pressable disabled={busy} style={s.button} onPress={()=>void action(()=>ZoryqMobileNode.start())}><Text style={s.buttonText}>Iniciar</Text></Pressable><Pressable disabled={busy} style={s.secondary} onPress={()=>void action(()=>ZoryqMobileNode.pause())}><Text style={s.secondaryText}>Pausar</Text></Pressable><Pressable disabled={busy} style={s.secondary} onPress={()=>void action(()=>ZoryqMobileNode.stop())}><Text style={s.secondaryText}>Parar</Text></Pressable></View></View>
  <View style={s.grid}><Metric label="STATUS" value={node.state}/><Metric label="CHAIN ID" value="5919065"/><Metric label="ÚLTIMO BLOCO" value={node.lastBlock>=0?String(node.lastBlock):'—'}/><Metric label="MODO" value={node.mode}/><Metric label="RPCs OK" value={String(node.rpcHealthyCount)}/><Metric label="ACORDO RPC" value={node.independentRpcAgreement?`${node.rpcAgreementVotes} votos`:'sem quorum'}/><Metric label="KEYSTORE" value={node.nodeKeyHardwareBacked?'HARDWARE':'ANDROID'}/><Metric label="XP VERIFICADO" value={serverXp===null?'—':String(serverXp)}/></View>
  {warning?<View style={s.warn}><Text style={s.warnTitle}>Mobile Node</Text><Text style={s.warnText}>{warning}</Text></View>:null}
  <View style={s.card}><Text style={s.cardTitle}>XP verificado pelo servidor</Text><Text style={s.copy}>Estado: {serverState}</Text><Text style={s.copy}>A Wallet não calcula nem concede XP localmente. O saldo exibido aqui só vem do servidor após validar a Node Identity, o challenge, a assinatura e o witness.</Text><View style={s.actions}><Pressable disabled={busy||!api} style={[s.button,!api&&s.disabled]} onPress={()=>void serverAction(registerNode)}><Text style={s.buttonText}>Registrar Node</Text></Pressable><Pressable disabled={busy||!api} style={[s.secondary,!api&&s.disabled]} onPress={()=>void serverAction(submitProof)}><Text style={s.secondaryText}>Enviar proof</Text></Pressable><Pressable disabled={busy||!api} style={[s.secondary,!api&&s.disabled]} onPress={()=>void serverAction(refreshXp)}><Text style={s.secondaryText}>Atualizar XP</Text></Pressable></View>{lastReward?<Text style={s.line}>Última reward: +{lastReward.xpAwarded} XP · bloco {lastReward.bestBlock} · serverVerified=true</Text>:null}</View>
  <View style={s.card}><Text style={s.cardTitle}>Modo de contribuição</Text><View style={s.actions}>{(['ECO','BALANCED','MAX_CONTRIBUTION','PAUSED'] as NodeMode[]).map(mode=><Pressable key={mode} style={[s.chip,node.mode===mode&&s.chipOn]} onPress={()=>void setMode(mode)}><Text style={s.chipText}>{mode.replace('_',' ')}</Text></Pressable>)}</View><Text style={s.copy}>Resource governor: {node.resourceDecision||'aguardando decisão'}</Text></View>
  <View style={s.card}><Text style={s.cardTitle}>Política ativa</Text><Text style={s.line}>✓ Bateria mínima: {node.minBatteryPct}%</Text><Text style={s.line}>✓ Charging only: {node.chargingOnly?'sim':'não'}</Text><Text style={s.line}>✓ Wi‑Fi only: {node.wifiOnly?'sim':'não'}</Text><Text style={s.line}>✓ Dados móveis: {node.mobileDataAllowed?'permitidos':'bloqueados'}</Text><Text style={s.line}>✓ Trabalho foreground permanece visível no Android</Text><Text style={s.line}>✓ Sem quorum independente, a observação continua com 0 XP</Text></View>
  <View style={s.proof}><Text style={s.proofTitle}>Identidade e última observação</Text><Text style={s.mono}>Node ID: {node.nodeId||'—'}{`\n`}Block: {node.lastBlock>=0?node.lastBlock:'—'}{`\n`}Hash: {node.lastHash||'—'}{`\n`}Checkpoint: {node.lastCheckpoint||'—'}{`\n`}Checked: {node.lastCheck||'—'}{`\n`}Independent RPC agreement: {String(node.independentRpcAgreement)}{`\n`}Local XP: {node.lastLocalProofXp} (must remain 0){`\n`}Server XP: {serverXp===null?'—':serverXp}</Text></View>
 </ScrollView></SafeAreaView>
}
function Metric({label,value}:{label:string;value:string}){return <View style={s.metric}><Text style={s.metricLabel}>{label}</Text><Text style={s.metricValue}>{value}</Text></View>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:ZORYQ_UI.background},content:{padding:18,paddingBottom:44},header:{flexDirection:'row',alignItems:'center',gap:16,marginBottom:18},back:{color:ZORYQ_UI.primary,fontWeight:'900'},kicker:{color:'#58E5CA',fontSize:10,fontWeight:'900',letterSpacing:1.4},title:{color:ZORYQ_UI.text,fontWeight:'900',fontSize:26},hero:{borderWidth:1,borderColor:ZORYQ_UI.border,borderRadius:22,padding:22,backgroundColor:ZORYQ_UI.panelSecondary},heroOn:{borderColor:'#35D49A'},state:{color:'#6FE6B1',fontSize:11,fontWeight:'900',letterSpacing:1.2},heroTitle:{color:ZORYQ_UI.text,fontSize:27,fontWeight:'900',marginTop:10},copy:{color:'#9FB0C4',fontSize:14,lineHeight:21,marginTop:8},actions:{flexDirection:'row',flexWrap:'wrap',gap:8,marginTop:16},button:{paddingVertical:12,paddingHorizontal:18,borderRadius:12,backgroundColor:'#35D49A'},buttonText:{color:'#06100D',fontWeight:'900'},secondary:{paddingVertical:12,paddingHorizontal:18,borderRadius:12,backgroundColor:'#303B4B'},secondaryText:{color:'#DCE8F4',fontWeight:'900'},disabled:{opacity:.45},chip:{paddingVertical:9,paddingHorizontal:11,borderRadius:10,borderWidth:1,borderColor:ZORYQ_UI.border},chipOn:{borderColor:'#35D49A',backgroundColor:'#132A24'},chipText:{color:'#C8D5E2',fontSize:11,fontWeight:'800'},grid:{flexDirection:'row',flexWrap:'wrap',gap:10,marginTop:14},metric:{width:'48%',borderWidth:1,borderColor:ZORYQ_UI.border,borderRadius:15,padding:14,backgroundColor:'#0D1420'},metricLabel:{color:'#72869F',fontSize:9,fontWeight:'900',letterSpacing:1},metricValue:{color:ZORYQ_UI.text,fontSize:14,fontWeight:'900',marginTop:5},warn:{marginTop:14,borderRadius:15,padding:14,backgroundColor:'#2A1A11',borderWidth:1,borderColor:'#684324'},warnTitle:{color:'#FFC977',fontWeight:'900'},warnText:{color:'#D4B98F',marginTop:5},card:{marginTop:14,borderRadius:18,padding:18,backgroundColor:'#0D1420',borderWidth:1,borderColor:ZORYQ_UI.border},cardTitle:{color:ZORYQ_UI.text,fontWeight:'900',fontSize:17,marginBottom:8},line:{color:'#A9B9CA',lineHeight:24},proof:{marginTop:14,borderRadius:18,padding:18,backgroundColor:'#070B11',borderWidth:1,borderColor:ZORYQ_UI.border},proofTitle:{color:'#67E7D1',fontWeight:'900',marginBottom:8},mono:{color:'#92A6BC',fontFamily:'monospace',fontSize:11,lineHeight:18}});
