import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Alert,Pressable,Share,StyleSheet,Text,View} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {Chess} from 'chess.js';

type GameId='hub'|'merge2048'|'chess'|'checkers'|'pulse'|'reflex'|'memory'|'tictactoe';
type Stats={played:number;wins:number;draws:number;losses:number;xp:number;best?:number};
type StatsMap=Record<string,Stats>;
type CheckPiece=null|'r'|'R'|'b'|'B';
type Dir='left'|'right'|'up'|'down';
type ReflexPhase='idle'|'waiting'|'go'|'done';

const KEY='zoriq.mini.games.v1';
const emptyStats:Stats={played:0,wins:0,draws:0,losses:0,xp:0,best:0};
const ACCENTS=['#63f5ff','#c8ff53','#a88cff','#ff9b54','#ff6fae','#5cffad','#68a7ff'];
const gameMeta:{id:Exclude<GameId,'hub'>;icon:string;name:string;desc:string;tag:string;accent:string}[]=[
 {id:'merge2048',icon:'◆',name:'Neon 2048',desc:'Combine blocos, crie combos e alcance 2048. Swipe ou use as setas.',tag:'PUZZLE',accent:'#63f5ff'},
 {id:'chess',icon:'♞',name:'Xadrez vs ZORI',desc:'Xadrez completo contra uma IA que prioriza tática, centro e material.',tag:'ESTRATÉGIA',accent:'#c8ff53'},
 {id:'checkers',icon:'⛀',name:'Damas vs ZORI',desc:'Capturas obrigatórias, múltiplos saltos, damas e adversário automático.',tag:'ESTRATÉGIA',accent:'#a88cff'},
 {id:'pulse',icon:'◉',name:'Pulse Sequence',desc:'Memorize uma sequência de pulsos cada vez maior e sobreviva até o nível 10.',tag:'MEMÓRIA',accent:'#ff6fae'},
 {id:'reflex',icon:'⚡',name:'Reflex Rush',desc:'Cinco rodadas de reação. Antecipe e você recebe penalidade; espere o sinal.',tag:'REFLEXO',accent:'#ff9b54'},
 {id:'memory',icon:'✦',name:'Memory Pro',desc:'Encontre os pares com combo, precisão e o menor número de jogadas.',tag:'FOCO',accent:'#5cffad'},
 {id:'tictactoe',icon:'✕',name:'Jogo da Velha Arena',desc:'Enfrente uma versão do ZORI que calcula as melhores respostas.',tag:'CLÁSSICO+',accent:'#68a7ff'}
];
const memorySymbols=['⚡','✦','◇','◉','☄','❄','🔥','△'];
const chessPieces:Record<string,string>={wp:'♙',wn:'♘',wb:'♗',wr:'♖',wq:'♕',wk:'♔',bp:'♟',bn:'♞',bb:'♝',br:'♜',bq:'♛',bk:'♚'};
const pieceValue:Record<string,number>={p:100,n:320,b:330,r:500,q:900,k:20000};

function winnerTTT(b:string[]){const lines=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];for(const [a,c,d] of lines)if(b[a]&&b[a]===b[c]&&b[a]===b[d])return b[a];return b.every(Boolean)?'D':null}
function minimaxTTT(board:string[],maximizing:boolean,depth=0):number{const w=winnerTTT(board);if(w==='O')return 10-depth;if(w==='X')return depth-10;if(w==='D')return 0;const open=board.map((v,i)=>v?null:i).filter((x):x is number=>x!==null);if(maximizing){let best=-99;for(const i of open){const n=[...board];n[i]='O';best=Math.max(best,minimaxTTT(n,false,depth+1))}return best}let best=99;for(const i of open){const n=[...board];n[i]='X';best=Math.min(best,minimaxTTT(n,true,depth+1))}return best}
function bestZoriMove(board:string[]){const open=board.map((v,i)=>v?null:i).filter((x):x is number=>x!==null);let best=-99,candidates:number[]=[];for(const i of open){const n=[...board];n[i]='O';const score=minimaxTTT(n,false);if(score>best){best=score;candidates=[i]}else if(score===best)candidates.push(i)}return candidates[Math.floor(Math.random()*Math.max(1,candidates.length))]}

function shuffledMemory(){const a=[...memorySymbols,...memorySymbols];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function fresh2048(){let b=Array(16).fill(0);b=addRandomTile(b);b=addRandomTile(b);return b}
function addRandomTile(board:number[]){const empty=board.map((v,i)=>v?null:i).filter((x):x is number=>x!==null);if(!empty.length)return board;const out=[...board],slot=empty[Math.floor(Math.random()*empty.length)];out[slot]=Math.random()<.9?2:4;return out}
function mergeLine(line:number[]){const compact=line.filter(Boolean),out:number[]=[],gain={value:0};for(let i=0;i<compact.length;i++){if(compact[i]===compact[i+1]){const v=compact[i]*2;out.push(v);gain.value+=v;i++}else out.push(compact[i])}while(out.length<4)out.push(0);return{line:out,gain:gain.value}}
function lineIndices(dir:Dir,k:number){if(dir==='left')return[k*4,k*4+1,k*4+2,k*4+3];if(dir==='right')return[k*4+3,k*4+2,k*4+1,k*4];if(dir==='up')return[k,k+4,k+8,k+12];return[k+12,k+8,k+4,k]}
function move2048(board:number[],dir:Dir){const out=[...board];let gain=0;for(let k=0;k<4;k++){const idx=lineIndices(dir,k),m=mergeLine(idx.map(i=>board[i]));gain+=m.gain;idx.forEach((i,j)=>out[i]=m.line[j])}const changed=out.some((v,i)=>v!==board[i]);return{board:changed?addRandomTile(out):board,gain,changed}}
function canMove2048(board:number[]){if(board.some(v=>v===0))return true;for(let r=0;r<4;r++)for(let c=0;c<4;c++){const i=r*4+c;if(c<3&&board[i]===board[i+1])return true;if(r<3&&board[i]===board[i+4])return true}return false}

function freshCheckers():CheckPiece[]{const b:Array<CheckPiece>=Array(64).fill(null);for(let r=0;r<3;r++)for(let c=0;c<8;c++)if((r+c)%2===1)b[r*8+c]='b';for(let r=5;r<8;r++)for(let c=0;c<8;c++)if((r+c)%2===1)b[r*8+c]='r';return b}
function dirsFor(p:CheckPiece){if(!p)return[] as number[];if(p==='R'||p==='B')return[-1,1];return p.toLowerCase()==='r'?[-1]:[1]}
function owner(p:CheckPiece){return p?.toLowerCase()||null}
function checkMoves(board:CheckPiece[],from:number,captureOnly=false){const p=board[from];if(!p)return[] as {to:number;capture?:number}[];const r=Math.floor(from/8),c=from%8,out:{to:number;capture?:number}[]=[];for(const dr of dirsFor(p))for(const dc of[-1,1]){const r1=r+dr,c1=c+dc;if(r1<0||r1>7||c1<0||c1>7)continue;const i1=r1*8+c1;if(!board[i1]&&!captureOnly)out.push({to:i1});else if(board[i1]&&owner(board[i1])!==owner(p)){const r2=r+dr*2,c2=c+dc*2;if(r2>=0&&r2<8&&c2>=0&&c2<8){const i2=r2*8+c2;if(!board[i2])out.push({to:i2,capture:i1})}}}return captureOnly?out.filter(x=>x.capture!=null):out}
function anyCapture(board:CheckPiece[],turn:'r'|'b'){return board.some((p,i)=>owner(p)===turn&&checkMoves(board,i,true).length>0)}
function hasAnyMove(board:CheckPiece[],turn:'r'|'b'){const must=anyCapture(board,turn);return board.some((p,i)=>owner(p)===turn&&checkMoves(board,i,must).length>0)}
function applyCheckMove(board:CheckPiece[],from:number,to:number,capture?:number){const b=[...board],moving=b[from];b[from]=null;b[to]=moving;if(capture!=null)b[capture]=null;const row=Math.floor(to/8);if(moving==='r'&&row===0)b[to]='R';if(moving==='b'&&row===7)b[to]='B';return b}
function aiCheckersTurn(start:CheckPiece[]){let board=[...start],from:number|undefined;for(let chain=0;chain<8;chain++){const must=from!=null?true:anyCapture(board,'b');const candidates:{from:number;to:number;capture?:number;score:number}[]=[];board.forEach((p,i)=>{if(owner(p)!=='b'||(from!=null&&i!==from))return;for(const m of checkMoves(board,i,must)){let score=(m.capture!=null?100:0)+Math.random()*12;const row=Math.floor(m.to/8);if(row===7&&p==='b')score+=45;if(p==='B')score+=8;score+=Math.max(0,4-Math.abs(3.5-(m.to%8)));candidates.push({from:i,to:m.to,capture:m.capture,score})}});if(!candidates.length)break;candidates.sort((a,b)=>b.score-a.score);const pick=candidates[0];board=applyCheckMove(board,pick.from,pick.to,pick.capture);if(pick.capture!=null&&checkMoves(board,pick.to,true).length){from=pick.to;continue}break}return board}

export default function PremiumArcade({mode='gaming',onEarnXp}:{mode?:'fun'|'gaming';onEarnXp?:(amount:number)=>void}){
 const [game,setGame]=useState<GameId>('hub');
 const [stats,setStats]=useState<StatsMap>({});
 const [loaded,setLoaded]=useState(false);
 const timers=useRef<ReturnType<typeof setTimeout>[]>([]);

 const [mergeBoard,setMergeBoard]=useState<number[]>(fresh2048());
 const [mergeScore,setMergeScore]=useState(0);
 const [mergeWon,setMergeWon]=useState(false);
 const [mergeDone,setMergeDone]=useState(false);
 const swipeStart=useRef<{x:number;y:number}|null>(null);

 const [chess,setChess]=useState(()=>new Chess());
 const [chessSelected,setChessSelected]=useState<string|null>(null);
 const [chessThinking,setChessThinking]=useState(false);
 const [chessDone,setChessDone]=useState(false);
 const chessEpoch=useRef(0);

 const [checkers,setCheckers]=useState<CheckPiece[]>(freshCheckers());
 const [checkTurn,setCheckTurn]=useState<'r'|'b'>('r');
 const [checkSelected,setCheckSelected]=useState<number|null>(null);
 const [checkWinner,setCheckWinner]=useState<'r'|'b'|null>(null);
 const checkEpoch=useRef(0);

 const [pulseSequence,setPulseSequence]=useState<number[]>([]);
 const [pulseInput,setPulseInput]=useState(0);
 const [pulseActive,setPulseActive]=useState<number|null>(null);
 const [pulseShowing,setPulseShowing]=useState(false);
 const [pulseLevel,setPulseLevel]=useState(0);
 const [pulseStatus,setPulseStatus]=useState('Toque em iniciar e memorize os pulsos.');
 const pulseEpoch=useRef(0);

 const [reflexPhase,setReflexPhase]=useState<ReflexPhase>('idle');
 const [reflexRound,setReflexRound]=useState(0);
 const [reflexTimes,setReflexTimes]=useState<number[]>([]);
 const [reflexAverage,setReflexAverage]=useState<number|null>(null);
 const reflexStart=useRef(0);
 const reflexTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const reflexEpoch=useRef(0);

 const [memory,setMemory]=useState<string[]>(shuffledMemory());
 const [memoryOpen,setMemoryOpen]=useState<number[]>([]);
 const [memoryMatched,setMemoryMatched]=useState<number[]>([]);
 const [memoryMoves,setMemoryMoves]=useState(0);
 const [memoryCombo,setMemoryCombo]=useState(0);
 const [memoryDone,setMemoryDone]=useState(false);
 const [memoryStarted,setMemoryStarted]=useState<number|null>(null);
 const [memorySeconds,setMemorySeconds]=useState(0);

 const [ttt,setTtt]=useState<string[]>(Array(9).fill(''));
 const [tttDone,setTttDone]=useState(false);

 useEffect(()=>{AsyncStorage.getItem(KEY).then(v=>{if(v)try{setStats(JSON.parse(v)||{})}catch{}setLoaded(true)})},[]);
 useEffect(()=>{if(loaded)AsyncStorage.setItem(KEY,JSON.stringify(stats))},[stats,loaded]);
 useEffect(()=>()=>{timers.current.forEach(clearTimeout);if(reflexTimer.current)clearTimeout(reflexTimer.current)},[]);

 function addResult(id:string,result:'win'|'draw'|'loss',xp:number,best?:number){setStats(s=>{const old=s[id]||emptyStats;return{...s,[id]:{...old,played:old.played+1,wins:old.wins+(result==='win'?1:0),draws:old.draws+(result==='draw'?1:0),losses:old.losses+(result==='loss'?1:0),xp:old.xp+xp,best:best==null?(old.best||0):Math.max(old.best||0,best)}}});onEarnXp?.(xp)}
 function later(fn:()=>void,ms:number){const t=setTimeout(fn,ms);timers.current.push(t);return t}
 function back(){setGame('hub')}
 async function shareChallenge(name:string){await Share.share({message:`Te desafio no ${name} da ZORYQ 🎮⚡ Consegue superar meu resultado?`}).catch(()=>{})}

 function reset2048(){setMergeBoard(fresh2048());setMergeScore(0);setMergeWon(false);setMergeDone(false)}
 function moveMerge(dir:Dir){if(mergeDone)return;const m=move2048(mergeBoard,dir);if(!m.changed)return;const nextScore=mergeScore+m.gain;setMergeBoard(m.board);setMergeScore(nextScore);const reached=m.board.some(v=>v>=2048);if(reached&&!mergeWon){setMergeWon(true);addResult('merge2048','win',40,nextScore);Alert.alert('2048 conquistado!','Excelente corrida. +40 XP')}if(!canMove2048(m.board)){setMergeDone(true);if(!reached&&!mergeWon)addResult('merge2048','loss',6,nextScore)}}
 function swipeEnd(e:any){if(!swipeStart.current)return;const {pageX,pageY}=e.nativeEvent;const dx=pageX-swipeStart.current.x,dy=pageY-swipeStart.current.y;swipeStart.current=null;if(Math.max(Math.abs(dx),Math.abs(dy))<28)return;moveMerge(Math.abs(dx)>Math.abs(dy)?(dx>0?'right':'left'):(dy>0?'down':'up'))}

 function resetChess(){chessEpoch.current++;setChess(new Chess());setChessSelected(null);setChessThinking(false);setChessDone(false)}
 function finishChess(g:Chess){if(!g.isGameOver()||chessDone)return false;setChessDone(true);setChessThinking(false);if(g.isCheckmate()){const playerWon=g.turn()==='b';addResult('chess',playerWon?'win':'loss',playerWon?35:5);Alert.alert(playerWon?'Xeque-mate!':'ZORI venceu',playerWon?'Você venceu a IA. +35 XP':'Boa partida. +5 XP de experiência')}else{addResult('chess','draw',12);Alert.alert('Empate','Partida encerrada. +12 XP')}return true}
 function chooseChessAiMove(g:Chess){const moves=g.moves({verbose:true}) as any[];if(!moves.length)return null;let best=-1e9,choices:any[]=[];for(const m of moves){let score=Math.random()*18+(m.captured?pieceValue[m.captured]*1.15:0)+(m.promotion?800:0);if(['d4','e4','d5','e5'].includes(m.to))score+=45;if(m.san?.includes('+'))score+=55;if(m.san?.includes('#'))score+=100000;if(score>best+1){best=score;choices=[m]}else if(Math.abs(score-best)<=1)choices.push(m)}return choices[Math.floor(Math.random()*choices.length)]}
 function tapChess(square:string){if(chessDone||chessThinking||chess.turn()!=='w')return;if(!chessSelected){const p=chess.get(square as any);if(p?.color==='w')setChessSelected(square);return}if(square===chessSelected){setChessSelected(null);return}const next=new Chess(chess.fen());try{const move=next.move({from:chessSelected as any,to:square as any,promotion:'q'});if(!move){setChessSelected(null);return}setChess(next);setChessSelected(null);if(next.isGameOver()){finishChess(next);return}setChessThinking(true);const epoch=++chessEpoch.current;later(()=>{if(epoch!==chessEpoch.current)return;const aiGame=new Chess(next.fen()),ai=chooseChessAiMove(aiGame);if(ai)aiGame.move({from:ai.from,to:ai.to,promotion:ai.promotion||'q'});setChess(aiGame);setChessThinking(false);finishChess(aiGame)},420)}catch{const p=chess.get(square as any);setChessSelected(p?.color==='w'?square:null)}}

 function resetCheckers(){checkEpoch.current++;setCheckers(freshCheckers());setCheckTurn('r');setCheckSelected(null);setCheckWinner(null)}
 function endCheckers(winner:'r'|'b'){setCheckWinner(winner);setCheckTurn(winner);const win=winner==='r';addResult('checkers',win?'win':'loss',win?30:5);Alert.alert(win?'Você venceu!':'ZORI venceu',win?'Domínio do tabuleiro. +30 XP':'Boa tentativa. +5 XP')}
 function scheduleCheckersAi(board:CheckPiece[]){setCheckTurn('b');const epoch=++checkEpoch.current;later(()=>{if(epoch!==checkEpoch.current)return;if(!hasAnyMove(board,'b')){endCheckers('r');return}const next=aiCheckersTurn(board);setCheckers(next);if(!next.some(x=>owner(x)==='r')||!hasAnyMove(next,'r')){endCheckers('b');return}setCheckTurn('r')},480)}
 function tapCheck(i:number){if(checkWinner||checkTurn!=='r')return;const p=checkers[i],must=anyCapture(checkers,'r');if(checkSelected==null){if(owner(p)==='r'&&(!must||checkMoves(checkers,i,true).length))setCheckSelected(i);return}if(i===checkSelected){setCheckSelected(null);return}const m=checkMoves(checkers,checkSelected,must).find(x=>x.to===i);if(!m){if(owner(p)==='r'&&(!must||checkMoves(checkers,i,true).length))setCheckSelected(i);return}const b=applyCheckMove(checkers,checkSelected,i,m.capture);setCheckers(b);if(m.capture!=null&&checkMoves(b,i,true).length){setCheckSelected(i);return}setCheckSelected(null);if(!b.some(x=>owner(x)==='b')||!hasAnyMove(b,'b')){endCheckers('r');return}scheduleCheckersAi(b)}

 function clearPulseTimers(){pulseEpoch.current++;setPulseActive(null);setPulseShowing(false)}
 function showPulse(seq:number[],epoch:number){setPulseShowing(true);setPulseInput(0);seq.forEach((pad,i)=>{later(()=>{if(epoch===pulseEpoch.current)setPulseActive(pad)},450+i*580);later(()=>{if(epoch===pulseEpoch.current)setPulseActive(null)},760+i*580)});later(()=>{if(epoch===pulseEpoch.current){setPulseShowing(false);setPulseStatus('Sua vez — repita a sequência.')}},380+seq.length*580)}
 function nextPulse(base:number[]){const seq=[...base,Math.floor(Math.random()*4)],epoch=++pulseEpoch.current;setPulseSequence(seq);setPulseLevel(seq.length);setPulseStatus(`Nível ${seq.length} · observe`);showPulse(seq,epoch)}
 function startPulse(){clearPulseTimers();setPulseSequence([]);setPulseLevel(0);setPulseInput(0);setPulseStatus('Preparando...');nextPulse([])}
 function tapPulse(pad:number){if(pulseShowing||!pulseSequence.length)return;setPulseActive(pad);later(()=>setPulseActive(a=>a===pad?null:a),150);if(pad!==pulseSequence[pulseInput]){const level=pulseLevel,xp=Math.max(3,level*2);addResult('pulse',level>=7?'draw':'loss',xp,level);setPulseStatus(`Sequência perdida no nível ${level}. +${xp} XP`);setPulseSequence([]);return}const nextIndex=pulseInput+1;if(nextIndex===pulseSequence.length){if(pulseLevel>=10){addResult('pulse','win',35,pulseLevel);setPulseStatus('Nível 10 concluído! +35 XP');setPulseSequence([]);return}setPulseStatus('Perfeito! Próximo nível...');later(()=>nextPulse(pulseSequence),520)}else setPulseInput(nextIndex)}

 function scheduleReflex(epoch:number){setReflexPhase('waiting');const delay=900+Math.floor(Math.random()*1700);if(reflexTimer.current)clearTimeout(reflexTimer.current);reflexTimer.current=setTimeout(()=>{if(epoch!==reflexEpoch.current)return;reflexStart.current=Date.now();setReflexPhase('go')},delay)}
 function finishReflex(results:number[]){const avg=Math.round(results.reduce((a,b)=>a+b,0)/results.length);setReflexAverage(avg);setReflexPhase('done');const outcome=avg<=280?'win':avg<=430?'draw':'loss',xp=avg<=280?28:avg<=430?14:6;addResult('reflex',outcome,xp,Math.max(0,1000-avg));}
 function advanceReflex(results:number[]){setReflexTimes(results);if(results.length>=5){finishReflex(results);return}setReflexRound(results.length+1);setReflexPhase('idle');const epoch=reflexEpoch.current;later(()=>scheduleReflex(epoch),420)}
 function startReflex(){reflexEpoch.current++;if(reflexTimer.current)clearTimeout(reflexTimer.current);setReflexTimes([]);setReflexAverage(null);setReflexRound(1);scheduleReflex(reflexEpoch.current)}
 function tapReflex(){if(reflexPhase==='waiting'){if(reflexTimer.current)clearTimeout(reflexTimer.current);advanceReflex([...reflexTimes,1000]);return}if(reflexPhase==='go'){advanceReflex([...reflexTimes,Math.max(80,Date.now()-reflexStart.current)])}}

 function resetMemory(){setMemory(shuffledMemory());setMemoryOpen([]);setMemoryMatched([]);setMemoryMoves(0);setMemoryCombo(0);setMemoryDone(false);setMemoryStarted(Date.now());setMemorySeconds(0)}
 function tapMemory(i:number){if(memoryDone||memoryMatched.includes(i)||memoryOpen.includes(i)||memoryOpen.length>=2)return;if(memoryStarted==null)setMemoryStarted(Date.now());const open=[...memoryOpen,i];setMemoryOpen(open);if(open.length===2){const nextMoves=memoryMoves+1;setMemoryMoves(nextMoves);const[a,b]=open;if(memory[a]===memory[b]){const matched=[...memoryMatched,a,b],combo=memoryCombo+1;setMemoryCombo(combo);setMemoryMatched(matched);setMemoryOpen([]);if(matched.length===memory.length){const seconds=Math.max(1,Math.round((Date.now()-(memoryStarted||Date.now()))/1000));setMemorySeconds(seconds);setMemoryDone(true);const xp=Math.max(12,44-Math.max(0,nextMoves-10)-Math.floor(seconds/12));addResult('memory','win',xp,Math.max(0,500-nextMoves*10-seconds));}}else{setMemoryCombo(0);later(()=>setMemoryOpen([]),620)}}

 function resetTtt(){setTtt(Array(9).fill(''));setTttDone(false)}
 function tapTtt(i:number){if(tttDone||ttt[i])return;const next=[...ttt];next[i]='X';const w=winnerTTT(next);if(w){finishTtt(next,w);return}const ai=bestZoriMove(next);if(ai!=null)next[ai]='O';finishTtt(next,winnerTTT(next))}
 function finishTtt(board:string[],w:string|null){setTtt(board);if(!w)return;setTttDone(true);if(w==='X'){addResult('tictactoe','win',22);Alert.alert('Vitória rara!','Você superou o ZORI. +22 XP')}else if(w==='O'){addResult('tictactoe','loss',4)}else addResult('tictactoe','draw',9)}

 const totalXp=Object.values(stats).reduce((a,b)=>a+(b?.xp||0),0);
 const totalPlayed=Object.values(stats).reduce((a,b)=>a+(b?.played||0),0);
 const totalWins=Object.values(stats).reduce((a,b)=>a+(b?.wins||0),0);
 const level=Math.floor(totalXp/100)+1,levelProgress=totalXp%100;
 const available=mode==='fun'?gameMeta.filter(g=>['merge2048','pulse','reflex','memory','tictactoe'].includes(g.id)):gameMeta;
 const daily=available[new Date().getDate()%available.length];

 if(game!=='hub')return <View style={s.wrap}><View style={s.gameTop}><Pressable onPress={back} style={s.back}><Text style={s.backText}>← Arcade</Text></Pressable><View style={{flex:1}}><Text style={s.gameTopTitle}>{gameMeta.find(x=>x.id===game)?.name}</Text><Text style={s.gameTopMeta}>ZORYQ PLAY · SKILL MODE</Text></View></View>{game==='merge2048'?<Merge2048/>:game==='chess'?<ChessGame/>:game==='checkers'?<Checkers/>:game==='pulse'?<Pulse/>:game==='reflex'?<Reflex/>:game==='memory'?<Memory/>:<TicTacToe/>}</View>;

 return <View style={s.wrap}><View style={s.hero}><View style={s.heroGlow}/><Text style={s.eyebrow}>{mode==='fun'?'ZORYQ QUICK PLAY':'ZORYQ ARCADE'}</Text><Text style={s.heroTitle}>{mode==='fun'?'Diversão rápida. Qualidade arcade.':'Jogue melhor. Suba de nível.'}</Text><Text style={s.copy}>Jogos de habilidade, estratégia, memória e reflexo com progressão local, XP e desafios sociais — sem tocar no saldo da sua wallet.</Text><View style={s.levelRow}><View style={{flex:1}}><Text style={s.levelLabel}>NÍVEL {level}</Text><View style={s.progress}><View style={[s.progressFill,{width:`${levelProgress}%`}]}/></View><Text style={s.meta}>{levelProgress}/100 XP para o próximo nível</Text></View><View style={s.levelOrb}><Text style={s.levelOrbText}>{level}</Text></View></View><View style={s.stats}><MiniStat n={String(totalPlayed)} l="partidas"/><MiniStat n={String(totalWins)} l="vitórias"/><MiniStat n={String(totalXp)} l="XP arcade"/></View></View>
 <View style={[s.featured,{borderColor:daily.accent}]}><View style={[s.featuredIcon,{backgroundColor:daily.accent}]}><Text style={s.featuredIconText}>{daily.icon}</Text></View><View style={{flex:1}}><Text style={s.tag}>DESTAQUE DO DIA</Text><Text style={s.featuredTitle}>{daily.name}</Text><Text style={s.meta}>{daily.desc}</Text></View><Pressable onPress={()=>setGame(daily.id)} style={[s.playRound,{borderColor:daily.accent}]}><Text style={[s.playRoundText,{color:daily.accent}]}>JOGAR</Text></Pressable></View>
 <View style={s.grid}>{available.map((g,index)=>{const st=stats[g.id]||emptyStats;return <View key={g.id} style={[s.card,{borderColor:`${g.accent}55`}]}><View style={[s.cardStripe,{backgroundColor:g.accent}]}/><View style={s.cardTop}><View style={[s.icon,{backgroundColor:`${g.accent}22`,borderColor:`${g.accent}66`}]}><Text style={[s.iconText,{color:g.accent}]}>{g.icon}</Text></View><View style={[s.tagPill,{borderColor:`${g.accent}66`}]}><Text style={[s.tag,{color:g.accent}]}>{g.tag}</Text></View></View><Text style={s.title}>{g.name}</Text><Text style={s.copy}>{g.desc}</Text><Text style={s.meta}>{st.played} partidas · {st.wins} vitórias · {st.xp} XP</Text><Pressable onPress={()=>setGame(g.id)} style={[s.primary,{backgroundColor:g.accent}]}><Text style={s.primaryText}>Jogar agora</Text></Pressable><Pressable onPress={()=>shareChallenge(g.name)} style={s.secondary}><Text style={s.secondaryText}>Desafiar amigo</Text></Pressable></View>})}</View>
 <View style={s.info}><Text style={s.infoTitle}>🏆 Próxima evolução competitiva</Text><Text style={s.copy}>A arquitetura mantém espaço para ranking entre amigos, temporadas, salas 1×1 e torneios. O resultado dos jogos continua separado de pagamentos e chaves da wallet.</Text></View></View>;

 function Merge2048(){const best=Math.max(stats.merge2048?.best||0,mergeScore);return <GameShell title="Neon 2048" subtitle={`Score ${mergeScore} · Best ${best}`}><View style={s.kpiRow}><Kpi label="OBJETIVO" value={mergeWon?'2048 ✓':'2048'}/><Kpi label="STATUS" value={mergeDone?'FIM':mergeWon?'CONQUISTADO':'ATIVO'}/></View><View style={s.mergeBoard} onStartShouldSetResponder={()=>true} onResponderGrant={(e:any)=>swipeStart.current={x:e.nativeEvent.pageX,y:e.nativeEvent.pageY}} onResponderRelease={swipeEnd}>{mergeBoard.map((v,i)=><View key={i} style={[s.mergeCell,v>0&&{backgroundColor:tileColor(v),borderColor:tileAccent(v)}]}><Text style={[s.mergeText,v>=128&&{fontSize:22}]}>{v||''}</Text></View>)}</View><View style={s.controls2048}><Arrow t="↑" onPress={()=>moveMerge('up')}/><View style={s.controlRow}><Arrow t="←" onPress={()=>moveMerge('left')}/><Arrow t="↓" onPress={()=>moveMerge('down')}/><Arrow t="→" onPress={()=>moveMerge('right')}/></View></View><Text style={s.note}>Deslize sobre o tabuleiro ou use as setas. Blocos iguais se fundem uma vez por movimento.</Text>{mergeDone?<Pressable onPress={reset2048} style={s.primary}><Text style={s.primaryText}>Nova corrida</Text></Pressable>:null}</GameShell>}
 function ChessGame(){const board=chess.board(),status=chessDone?(chess.isCheckmate()?(chess.turn()==='b'?'VOCÊ VENCEU':'ZORI VENCEU'):'EMPATE'):chessThinking?'ZORI pensando...':chess.inCheck()?'XEQUE · sua vez':'Sua vez · peças brancas';const targets=new Set(!chessThinking&&chessSelected?(chess.moves({square:chessSelected as any,verbose:true}) as any[]).map(m=>m.to):[]);return <GameShell title="Xadrez vs ZORI" subtitle={status} actions={<Pressable onPress={resetChess} style={s.secondary}><Text style={s.secondaryText}>Reiniciar</Text></Pressable>}><View style={s.chessBoard}>{board.flat().map((p:any,i)=>{const row=Math.floor(i/8),col=i%8,sq=`${String.fromCharCode(97+col)}${8-row}`,dark=(row+col)%2===1;return <Pressable key={sq} onPress={()=>tapChess(sq)} style={[s.chessCell,dark?s.boardDark:s.boardLight,chessSelected===sq&&s.selected,targets.has(sq)&&s.target]}><Text style={[s.chessPiece,p?.color==='b'&&s.blackPiece]}>{p?chessPieces[`${p.color}${p.type}`]:targets.has(sq)?'•':''}</Text></Pressable>})}</View><Text style={s.note}>Você joga com as brancas. Regras, xeque, roque, promoção e legalidade são validados pelo engine de xadrez; o ZORI responde automaticamente.</Text></GameShell>}
 function Checkers(){const legal=new Set(checkSelected==null?[]:checkMoves(checkers,checkSelected,anyCapture(checkers,'r')).map(x=>x.to));return <GameShell title="Damas vs ZORI" subtitle={checkWinner?(checkWinner==='r'?'VOCÊ VENCEU':'ZORI VENCEU'):checkTurn==='b'?'ZORI calculando...':`Sua vez${anyCapture(checkers,'r')?' · captura obrigatória':''}`} actions={<Pressable onPress={resetCheckers} style={s.secondary}><Text style={s.secondaryText}>Reiniciar</Text></Pressable>}><View style={s.checkBoard}>{checkers.map((p,i)=>{const r=Math.floor(i/8),c=i%8,dark=(r+c)%2===1;return <Pressable key={i} onPress={()=>tapCheck(i)} style={[s.checkCell,dark?s.boardDark:s.boardLight,checkSelected===i&&s.selected,legal.has(i)&&s.target]}>{p?<View style={[s.checkPiece,owner(p)==='r'?s.redPiece:s.bluePiece]}><Text style={s.king}>{p===p?.toUpperCase()?'♛':''}</Text></View>:null}</Pressable>})}</View><Text style={s.note}>Você controla as peças vermelhas. Capturas são obrigatórias, sequências de captura continuam na mesma jogada e a IA joga com as azuis.</Text></GameShell>}
 function Pulse(){return <GameShell title="Pulse Sequence" subtitle={pulseStatus} actions={<Pressable onPress={startPulse} style={s.secondary}><Text style={s.secondaryText}>{pulseLevel?'Reiniciar':'Iniciar'}</Text></Pressable>}><View style={s.pulseGrid}>{[0,1,2,3].map((pad)=><Pressable key={pad} disabled={pulseShowing} onPress={()=>tapPulse(pad)} style={[s.pulsePad,{borderColor:ACCENTS[pad+1]},pulseActive===pad&&{backgroundColor:ACCENTS[pad+1],transform:[{scale:.96}]}]}><Text style={[s.pulsePadText,{color:pulseActive===pad?'#081018':ACCENTS[pad+1]}]}>{['◆','●','▲','✦'][pad]}</Text></Pressable>)}</View><View style={s.kpiRow}><Kpi label="NÍVEL" value={String(pulseLevel)}/><Kpi label="META" value="10"/><Kpi label="SEQUÊNCIA" value={pulseSequence.length?`${pulseInput}/${pulseSequence.length}`:'—'}/></View></GameShell>}
 function Reflex(){const label=reflexPhase==='waiting'?'ESPERE...':reflexPhase==='go'?'TOQUE AGORA!':reflexPhase==='done'?'CONCLUÍDO':'INICIAR';return <GameShell title="Reflex Rush" subtitle={reflexAverage!=null?`Média ${reflexAverage} ms · ${reflexAverage<=280?'Elite':reflexAverage<=430?'Rápido':'Treine mais'}`:`Rodada ${reflexRound||0}/5`}><Pressable onPress={reflexPhase==='idle'&&reflexRound===0?startReflex:tapReflex} disabled={reflexPhase==='done'||(reflexPhase==='idle'&&reflexRound>0)} style={[s.reflexZone,reflexPhase==='waiting'&&s.reflexWaiting,reflexPhase==='go'&&s.reflexGo]}><Text style={s.reflexLabel}>{label}</Text><Text style={s.reflexHint}>{reflexPhase==='waiting'?'Não toque antes do sinal':reflexPhase==='go'?'AGORA!':reflexPhase==='done'?`${reflexTimes.join(' · ')} ms`:'Toque para começar 5 rodadas'}</Text></Pressable>{reflexPhase==='done'?<Pressable onPress={startReflex} style={s.primary}><Text style={s.primaryText}>Tentar novamente</Text></Pressable>:null}</GameShell>}
 function Memory(){return <GameShell title="Memory Pro" subtitle={`${memoryMoves} jogadas · ${memoryMatched.length/2}/8 pares · combo ${memoryCombo}×`} actions={<Pressable onPress={resetMemory} style={s.secondary}><Text style={s.secondaryText}>Embaralhar</Text></Pressable>}><View style={s.memory}>{memory.map((v,i)=>{const open=memoryOpen.includes(i)||memoryMatched.includes(i);return <Pressable key={i} onPress={()=>tapMemory(i)} style={[s.memoryCell,open&&s.memoryOpen,memoryMatched.includes(i)&&s.memoryMatched]}><Text style={s.memoryText}>{open?v:'?'}</Text></Pressable>})}</View>{memoryDone?<View style={s.result}><Text style={s.resultTitle}>Tabuleiro perfeito ✦</Text><Text style={s.copy}>{memoryMoves} jogadas · {memorySeconds}s · tente reduzir os dois números na próxima corrida.</Text></View>:null}</GameShell>}
 function TicTacToe(){const w=winnerTTT(ttt);return <GameShell title="Jogo da Velha Arena" subtitle={w?w==='D'?'Empate calculado':w==='X'?'Você venceu':'ZORI venceu':'Você é X · ZORI calcula a resposta'} actions={<Pressable onPress={resetTtt} style={s.secondary}><Text style={s.secondaryText}>Nova partida</Text></Pressable>}><View style={s.ttt}>{ttt.map((v,i)=><Pressable key={i} onPress={()=>tapTtt(i)} style={s.tttCell}><Text style={[s.tttText,v==='X'?s.cyan:s.lime]}>{v}</Text></Pressable>)}</View><Text style={s.note}>O ZORI usa minimax para avaliar as continuações. Empatar já exige jogo correto; vencer só acontece se a posição permitir.</Text></GameShell>}
}

function tileColor(v:number){if(v>=2048)return'#6d5a10';if(v>=512)return'#53306d';if(v>=128)return'#154c62';if(v>=32)return'#25403d';if(v>=8)return'#263348';return'#182334'}
function tileAccent(v:number){if(v>=2048)return'#ffe166';if(v>=512)return'#d68cff';if(v>=128)return'#63f5ff';if(v>=32)return'#5cffad';return'#68a7ff'}
function GameShell({title,subtitle,actions,children}:{title:string;subtitle:string;actions?:React.ReactNode;children:React.ReactNode}){return <View><View style={s.gameHeader}><View style={{flex:1}}><Text style={s.title}>{title}</Text><Text style={s.meta}>{subtitle}</Text></View>{actions}</View>{children}<View style={s.safe}><Text style={s.safeTitle}>🎮 ZORYQ Play</Text><Text style={s.meta}>Entretenimento e XP. Sem apostas, sem custódia e sem risco de saldo da wallet.</Text></View></View>}
function MiniStat({n,l}:{n:string;l:string}){return <View style={s.stat}><Text style={s.statN}>{n}</Text><Text style={s.statL}>{l}</Text></View>}
function Kpi({label,value}:{label:string;value:string}){return <View style={s.kpi}><Text style={s.kpiLabel}>{label}</Text><Text style={s.kpiValue}>{value}</Text></View>}
function Arrow({t,onPress}:{t:string;onPress:()=>void}){return <Pressable onPress={onPress} style={s.arrow}><Text style={s.arrowText}>{t}</Text></Pressable>}

const s=StyleSheet.create({
 wrap:{gap:11},
 hero:{backgroundColor:'#0b1020',borderWidth:1,borderColor:'#29365a',borderRadius:24,padding:19,overflow:'hidden'},heroGlow:{position:'absolute',width:190,height:190,borderRadius:190,right:-55,top:-75,backgroundColor:'#17394c',opacity:.72},eyebrow:{color:'#63f5ff',fontSize:10,fontWeight:'900',letterSpacing:1.8},heroTitle:{color:'#fff',fontSize:29,lineHeight:33,fontWeight:'900',marginVertical:8},copy:{color:'#a2aec2',fontSize:12,lineHeight:18},
 levelRow:{flexDirection:'row',alignItems:'center',gap:12,marginTop:15,backgroundColor:'#090d16',borderRadius:16,padding:12,borderWidth:1,borderColor:'#202c42'},levelLabel:{color:'#c8ff53',fontWeight:'900',fontSize:11,letterSpacing:1},progress:{height:7,backgroundColor:'#1b2535',borderRadius:99,overflow:'hidden',marginTop:7},progressFill:{height:'100%',backgroundColor:'#c8ff53',borderRadius:99},levelOrb:{width:48,height:48,borderRadius:17,backgroundColor:'#c8ff53',alignItems:'center',justifyContent:'center'},levelOrbText:{color:'#091007',fontSize:20,fontWeight:'900'},
 stats:{flexDirection:'row',gap:7,marginTop:12},stat:{flex:1,backgroundColor:'#080c14',borderRadius:13,padding:10,borderWidth:1,borderColor:'#1f2a3d'},statN:{color:'#fff',fontWeight:'900',fontSize:17},statL:{color:'#718098',fontSize:9,marginTop:2},
 featured:{backgroundColor:'#0d1320',borderWidth:1,borderRadius:18,padding:12,flexDirection:'row',alignItems:'center',gap:11},featuredIcon:{width:48,height:48,borderRadius:15,alignItems:'center',justifyContent:'center'},featuredIconText:{color:'#071018',fontSize:24,fontWeight:'900'},featuredTitle:{color:'#fff',fontSize:16,fontWeight:'900',marginVertical:3},playRound:{borderWidth:1,borderRadius:11,paddingHorizontal:10,paddingVertical:9},playRoundText:{fontSize:9,fontWeight:'900'},
 grid:{flexDirection:'row',flexWrap:'wrap',gap:9},card:{width:'48%',backgroundColor:'#0b1019',borderWidth:1,borderRadius:18,padding:13,overflow:'hidden'},cardStripe:{position:'absolute',left:0,right:0,top:0,height:3},cardTop:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:6},icon:{width:48,height:48,borderRadius:15,borderWidth:1,alignItems:'center',justifyContent:'center',marginBottom:8},iconText:{fontSize:25,fontWeight:'900'},tagPill:{borderWidth:1,borderRadius:99,paddingHorizontal:7,paddingVertical:4},tag:{fontSize:8,fontWeight:'900',letterSpacing:1.1},title:{color:'#fff',fontSize:19,fontWeight:'900',marginTop:5},meta:{color:'#79869c',fontSize:10,lineHeight:15,marginTop:4},primary:{backgroundColor:'#c8ff53',borderRadius:11,paddingVertical:11,paddingHorizontal:10,alignItems:'center',marginTop:10},primaryText:{color:'#071000',fontWeight:'900',fontSize:10},secondary:{borderWidth:1,borderColor:'#334158',borderRadius:11,paddingVertical:9,paddingHorizontal:10,alignItems:'center',marginTop:7,backgroundColor:'#0d1420'},secondaryText:{color:'#fff',fontWeight:'800',fontSize:10},
 info:{backgroundColor:'#0b1119',borderWidth:1,borderColor:'#27344b',borderRadius:16,padding:14},infoTitle:{color:'#fff',fontWeight:'900',marginBottom:4},gameTop:{flexDirection:'row',alignItems:'center',gap:10,marginBottom:4},back:{borderWidth:1,borderColor:'#334158',paddingHorizontal:10,paddingVertical:9,borderRadius:11,backgroundColor:'#0c121d'},backText:{color:'#fff',fontWeight:'800',fontSize:10},gameTopTitle:{color:'#fff',fontWeight:'900',fontSize:17},gameTopMeta:{color:'#63f5ff',fontSize:8,fontWeight:'900',letterSpacing:1,marginTop:2},gameHeader:{backgroundColor:'#0d1320',borderWidth:1,borderColor:'#28354b',borderRadius:17,padding:13,flexDirection:'row',alignItems:'center',gap:10,marginBottom:10},safe:{backgroundColor:'#0a1119',borderWidth:1,borderColor:'#26334a',borderRadius:14,padding:12,marginTop:12},safeTitle:{color:'#c8ff53',fontWeight:'900',fontSize:11},note:{color:'#718098',fontSize:9,lineHeight:14,marginTop:8},
 kpiRow:{flexDirection:'row',gap:7,marginBottom:10},kpi:{flex:1,backgroundColor:'#0b111b',borderWidth:1,borderColor:'#253247',borderRadius:12,padding:9},kpiLabel:{color:'#6f7e94',fontSize:8,fontWeight:'900',letterSpacing:1},kpiValue:{color:'#fff',fontSize:14,fontWeight:'900',marginTop:3},
 mergeBoard:{width:'100%',maxWidth:360,aspectRatio:1,alignSelf:'center',backgroundColor:'#070b12',borderWidth:1,borderColor:'#2b3950',borderRadius:17,padding:7,flexDirection:'row',flexWrap:'wrap',gap:'1%'},mergeCell:{width:'24.25%',height:'24.25%',backgroundColor:'#111927',borderWidth:1,borderColor:'#202c40',borderRadius:12,alignItems:'center',justifyContent:'center'},mergeText:{color:'#fff',fontSize:27,fontWeight:'900'},controls2048:{alignItems:'center',marginTop:11,gap:6},controlRow:{flexDirection:'row',gap:6},arrow:{width:54,height:42,borderWidth:1,borderColor:'#34445c',borderRadius:12,backgroundColor:'#0f1724',alignItems:'center',justifyContent:'center'},arrowText:{color:'#63f5ff',fontSize:21,fontWeight:'900'},
 chessBoard:{width:'100%',maxWidth:360,aspectRatio:1,alignSelf:'center',flexDirection:'row',flexWrap:'wrap',borderRadius:13,overflow:'hidden',borderWidth:1,borderColor:'#34445d'},chessCell:{width:'12.5%',height:'12.5%',alignItems:'center',justifyContent:'center'},boardLight:{backgroundColor:'#d9e1ee'},boardDark:{backgroundColor:'#52677f'},selected:{borderWidth:3,borderColor:'#c8ff53'},target:{borderWidth:3,borderColor:'#63f5ff'},chessPiece:{fontSize:31,color:'#101923'},blackPiece:{color:'#05080e'},
 checkBoard:{width:'100%',maxWidth:360,aspectRatio:1,alignSelf:'center',flexDirection:'row',flexWrap:'wrap',borderRadius:13,overflow:'hidden',borderWidth:1,borderColor:'#34445d'},checkCell:{width:'12.5%',height:'12.5%',alignItems:'center',justifyContent:'center'},checkPiece:{width:'72%',height:'72%',borderRadius:999,borderWidth:3,alignItems:'center',justifyContent:'center'},redPiece:{backgroundColor:'#f05f72',borderColor:'#ffc0ca'},bluePiece:{backgroundColor:'#3d78e7',borderColor:'#b5caff'},king:{color:'#fff',fontWeight:'900'},
 pulseGrid:{flexDirection:'row',flexWrap:'wrap',gap:9,justifyContent:'center',maxWidth:360,alignSelf:'center'},pulsePad:{width:'47%',aspectRatio:1,borderWidth:2,borderRadius:25,backgroundColor:'#0d1420',alignItems:'center',justifyContent:'center'},pulsePadText:{fontSize:37,fontWeight:'900'},
 reflexZone:{minHeight:245,borderRadius:24,borderWidth:2,borderColor:'#334158',backgroundColor:'#0b111b',alignItems:'center',justifyContent:'center',padding:20},reflexWaiting:{backgroundColor:'#31151a',borderColor:'#ff6f82'},reflexGo:{backgroundColor:'#123623',borderColor:'#5cffad'},reflexLabel:{color:'#fff',fontSize:31,fontWeight:'900',letterSpacing:1},reflexHint:{color:'#a5b0c2',fontSize:11,marginTop:8,textAlign:'center'},
 memory:{flexDirection:'row',flexWrap:'wrap',gap:6,justifyContent:'center'},memoryCell:{width:'22%',aspectRatio:1,backgroundColor:'#111925',borderWidth:1,borderColor:'#2d3a50',borderRadius:13,alignItems:'center',justifyContent:'center'},memoryOpen:{backgroundColor:'#15364a',borderColor:'#63f5ff'},memoryMatched:{backgroundColor:'#17382e',borderColor:'#5cffad'},memoryText:{fontSize:25,color:'#fff',fontWeight:'900'},result:{backgroundColor:'#101f1b',borderWidth:1,borderColor:'#315444',borderRadius:14,padding:13,marginTop:10},resultTitle:{color:'#5cffad',fontSize:17,fontWeight:'900'},
 ttt:{width:'100%',maxWidth:330,aspectRatio:1,alignSelf:'center',flexDirection:'row',flexWrap:'wrap',borderWidth:1,borderColor:'#35445c',borderRadius:17,overflow:'hidden'},tttCell:{width:'33.3333%',height:'33.3333%',borderWidth:.5,borderColor:'#35445c',alignItems:'center',justifyContent:'center',backgroundColor:'#0a1019'},tttText:{fontSize:52,fontWeight:'900'},cyan:{color:'#63f5ff'},lime:{color:'#c8ff53'}
});
