import React,{useCallback,useEffect,useState} from 'react';
import {Alert,Pressable,StyleSheet,Text,TextInput,View} from 'react-native';
import {createPost,getBackendState,listVisibleFeed,reportContent,hidePost,subscribeSocial,stopSocialSubscription,toggleBookmark,toggleLike,type SocialPost} from './socialBackend';

function friendly(e:any){const m=String(e?.message||e||'Falha');if(m.includes('auth_required'))return'Entre com sua wallet no topo do Social para publicar e interagir.';return m.slice(0,180)}
function when(v:string){try{return new Date(v).toLocaleString('pt-BR',{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'})}catch{return''}}

export default function SyncedFeed(){
 const [posts,setPosts]=useState<SocialPost[]>([]);const [compose,setCompose]=useState('');const [auth,setAuth]=useState(false);const [loading,setLoading]=useState(true);
 const refresh=useCallback(async()=>{try{const [state,rows]=await Promise.all([getBackendState(),listVisibleFeed(25)]);setAuth(state.authenticated);setPosts(rows)}catch{}finally{setLoading(false)}},[]);
 useEffect(()=>{let channel:any;let active=true;(async()=>{await refresh();if(!active)return;try{const state=await getBackendState();channel=subscribeSocial(()=>{if(active)refresh()},state.session?.user.id)}catch{}})();return()=>{active=false;if(channel)stopSocialSubscription(channel).catch(()=>{})}},[refresh]);
 async function publish(){const text=compose.trim();if(!text)return;if(!auth)return Alert.alert('ZORIQ Social','Entre com sua wallet no topo do Social para publicar no feed compartilhado.');try{await createPost(text);setCompose('');await refresh()}catch(e:any){Alert.alert('Publicar',friendly(e))}}
 async function action(fn:()=>Promise<any>){if(!auth)return Alert.alert('ZORIQ Social','Entre com sua wallet para sincronizar esta ação.');try{await fn();await refresh()}catch(e:any){Alert.alert('Social',friendly(e))}}
 return <View style={s.wrap}><View style={s.head}><View><Text style={s.eyebrow}>REDE SINCRONIZADA</Text><Text style={s.title}>Web ↔ APK</Text></View><Text style={[s.state,auth?s.on:s.public]}>{auth?'● conectado':'● leitura pública'}</Text></View><Text style={s.copy}>Posts deste bloco vêm do backend compartilhado e respeitam RLS. O restante do feed experimental continua disponível abaixo.</Text><View style={s.composer}><TextInput multiline value={compose} onChangeText={setCompose} maxLength={500} placeholder={auth?'Publique para web e APK…':'Entre com a wallet para publicar…'} placeholderTextColor="#697487" style={s.input}/><Pressable onPress={publish} style={s.primary}><Text style={s.primaryText}>Publicar sincronizado</Text></Pressable></View>{loading?<Text style={s.copy}>Carregando feed compartilhado…</Text>:posts.length?posts.map(p=><View key={p.id} style={s.post}><View style={s.row}><Text style={s.tag}>SINCRONIZADO</Text><Text style={s.time}>{when(p.created_at)}</Text></View><Text style={s.body}>{p.body||''}</Text><View style={s.actions}><Pressable onPress={()=>action(()=>toggleLike(p.id))}><Text style={s.action}>♡ {p.likes_count||0}</Text></Pressable><Pressable onPress={()=>action(()=>toggleBookmark(p.id))}><Text style={s.action}>☆ salvar</Text></Pressable><Pressable onPress={()=>action(()=>hidePost(p.id))}><Text style={s.action}>ocultar</Text></Pressable><Pressable onPress={()=>action(()=>reportContent('post',p.id,'other','Denúncia pelo APK'))}><Text style={s.report}>denunciar</Text></Pressable></View></View>):<Text style={s.copy}>Ainda não há posts compartilhados visíveis.</Text>}</View>
}
const s=StyleSheet.create({wrap:{backgroundColor:'#0b1017',borderWidth:1,borderColor:'#244657',borderRadius:18,padding:14,marginBottom:10},head:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},eyebrow:{color:'#34e8ff',fontSize:9,fontWeight:'900',letterSpacing:1.4},title:{color:'#fff',fontSize:20,fontWeight:'900',marginTop:3},state:{fontSize:9,fontWeight:'900',borderWidth:1,borderRadius:999,paddingHorizontal:8,paddingVertical:5},on:{color:'#5cffad',borderColor:'#315b40'},public:{color:'#34e8ff',borderColor:'#315569'},copy:{color:'#8390a3',fontSize:10,lineHeight:16,marginTop:8},composer:{marginTop:12},input:{color:'#fff',minHeight:58,textAlignVertical:'top',borderWidth:1,borderColor:'#293241',backgroundColor:'#090c12',borderRadius:12,padding:11},primary:{backgroundColor:'#baff45',padding:10,borderRadius:11,alignItems:'center',marginTop:7},primaryText:{color:'#071000',fontWeight:'900',fontSize:11},post:{backgroundColor:'#0e121a',borderWidth:1,borderColor:'#263442',borderRadius:14,padding:12,marginTop:9},row:{flexDirection:'row',justifyContent:'space-between'},tag:{color:'#5cffad',fontSize:8,fontWeight:'900',letterSpacing:1},time:{color:'#687386',fontSize:8},body:{color:'#f1f4f8',fontSize:13,lineHeight:20,marginVertical:10},actions:{flexDirection:'row',gap:14,flexWrap:'wrap'},action:{color:'#94a1b4',fontSize:10,fontWeight:'700'},report:{color:'#ff909e',fontSize:10,fontWeight:'700'}});
