org.gradle.jvmargs=-Xmx256m -XX:MaxMetaspaceSize=128m -XX:ReservedCodeCacheSize=64m -Xss512k -Dfile.encoding=UTF-8 -Dorg.gradle.vfs.watch=false
org.gradle.daemon=false
org.gradle.parallel=false
org.gradle.workers.max=1
org.gradle.caching=false
android.useAndroidX=true
android.enableJetifier=false
android.nonTransitiveRClass=true
