name: Deploy ZORYQ Testnet Contracts

'on':
  push:
    branches:
      - zoryq-evm-testnet-node
    paths:
      - .github/workflows/zoryq-deploy-testnet-contracts.yml
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Workflow parser check
        run: echo "ZORYQ deploy workflow is active"
